provider_info:
  - name: openai
    base_url: https://api.openai.com
    api_key: sk-xxxx
    protocol: 1
    models:
      - name: GPT-4o
        id: gpt-4o
        is_default: true
        think:
          enabled: true
          effort: 3
        token:
          context_tokens: 128000
          response_tokens: 4096
      - name: GPT-4o mini
        id: gpt-4o-mini
        is_default: false
        think:
          enabled: false
          effort: 0
        token:
          context_tokens: 128000
          response_tokens: 4096
  - name: anthropic
    base_url: https://api.anthropic.com
    api_key: sk-ant-xxxx
    protocol: 2
    models:
      - name: Claude Sonnet 4
        id: claude-sonnet-4-20250514
        is_default: false
        think:
          enabled: true
          effort: 2
        token:
          context_tokens: 200000
          response_tokens: 8192
