// Code generated by ent, DO NOT EDIT.

package kaguyachatblock

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the kaguyachatblock type in the database.
	Label = "kaguya_chat_block"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTurnID holds the string denoting the turn_id field in the database.
	FieldTurnID = "turn_id"
	// FieldSequence holds the string denoting the sequence field in the database.
	FieldSequence = "sequence"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldToolCallID holds the string denoting the tool_call_id field in the database.
	FieldToolCallID = "tool_call_id"
	// FieldToolName holds the string denoting the tool_name field in the database.
	FieldToolName = "tool_name"
	// FieldInput holds the string denoting the input field in the database.
	FieldInput = "input"
	// FieldOutput holds the string denoting the output field in the database.
	FieldOutput = "output"
	// FieldProviderExecuted holds the string denoting the provider_executed field in the database.
	FieldProviderExecuted = "provider_executed"
	// FieldIsError holds the string denoting the is_error field in the database.
	FieldIsError = "is_error"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldStartOrder holds the string denoting the start_order field in the database.
	FieldStartOrder = "start_order"
	// FieldEndOrder holds the string denoting the end_order field in the database.
	FieldEndOrder = "end_order"
	// EdgeTurn holds the string denoting the turn edge name in mutations.
	EdgeTurn = "turn"
	// Table holds the table name of the kaguyachatblock in the database.
	Table = "kaguya_chat_block"
	// TurnTable is the table that holds the turn relation/edge.
	TurnTable = "kaguya_chat_block"
	// TurnInverseTable is the table name for the KaguyaChatTurn entity.
	// It exists in this package in order to avoid circular dependency with the "kaguyachatturn" package.
	TurnInverseTable = "kaguya_chat_turn"
	// TurnColumn is the table column denoting the turn relation/edge.
	TurnColumn = "turn_id"
)

// Columns holds all SQL columns for kaguyachatblock fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTurnID,
	FieldSequence,
	FieldType,
	FieldText,
	FieldToolCallID,
	FieldToolName,
	FieldInput,
	FieldOutput,
	FieldProviderExecuted,
	FieldIsError,
	FieldErrorMessage,
	FieldStartedAt,
	FieldFinishedAt,
	FieldStartOrder,
	FieldEndOrder,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lyonmu/kaguya/internal/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TurnIDValidator is a validator for the "turn_id" field. It is called by the builders before save.
	TurnIDValidator func(string) error
	// SequenceValidator is a validator for the "sequence" field. It is called by the builders before save.
	SequenceValidator func(int64) error
	// DefaultText holds the default value on creation for the "text" field.
	DefaultText string
	// DefaultToolCallID holds the default value on creation for the "tool_call_id" field.
	DefaultToolCallID string
	// DefaultToolName holds the default value on creation for the "tool_name" field.
	DefaultToolName string
	// DefaultInput holds the default value on creation for the "input" field.
	DefaultInput string
	// DefaultProviderExecuted holds the default value on creation for the "provider_executed" field.
	DefaultProviderExecuted bool
	// DefaultIsError holds the default value on creation for the "is_error" field.
	DefaultIsError bool
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
	// StartOrderValidator is a validator for the "start_order" field. It is called by the builders before save.
	StartOrderValidator func(int64) error
	// EndOrderValidator is a validator for the "end_order" field. It is called by the builders before save.
	EndOrderValidator func(int64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeText      Type = "text"
	TypeReasoning Type = "reasoning"
	TypeToolCall  Type = "tool_call"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeText, TypeReasoning, TypeToolCall:
		return nil
	default:
		return fmt.Errorf("kaguyachatblock: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the KaguyaChatBlock queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTurnID orders the results by the turn_id field.
func ByTurnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurnID, opts...).ToFunc()
}

// BySequence orders the results by the sequence field.
func BySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequence, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByToolCallID orders the results by the tool_call_id field.
func ByToolCallID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolCallID, opts...).ToFunc()
}

// ByToolName orders the results by the tool_name field.
func ByToolName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolName, opts...).ToFunc()
}

// ByInput orders the results by the input field.
func ByInput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInput, opts...).ToFunc()
}

// ByProviderExecuted orders the results by the provider_executed field.
func ByProviderExecuted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderExecuted, opts...).ToFunc()
}

// ByIsError orders the results by the is_error field.
func ByIsError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsError, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByStartOrder orders the results by the start_order field.
func ByStartOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartOrder, opts...).ToFunc()
}

// ByEndOrder orders the results by the end_order field.
func ByEndOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndOrder, opts...).ToFunc()
}

// ByTurnField orders the results by turn field.
func ByTurnField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTurnStep(), sql.OrderByField(field, opts...))
	}
}
func newTurnStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TurnInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TurnTable, TurnColumn),
	)
}
