// Code generated by ent, DO NOT EDIT.

package kaguyachatblock

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lyonmu/kaguya/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldDeletedAt, v))
}

// TurnID applies equality check predicate on the "turn_id" field. It's identical to TurnIDEQ.
func TurnID(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldTurnID, v))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldSequence, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldText, v))
}

// ToolCallID applies equality check predicate on the "tool_call_id" field. It's identical to ToolCallIDEQ.
func ToolCallID(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldToolCallID, v))
}

// ToolName applies equality check predicate on the "tool_name" field. It's identical to ToolNameEQ.
func ToolName(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldToolName, v))
}

// Input applies equality check predicate on the "input" field. It's identical to InputEQ.
func Input(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldInput, v))
}

// ProviderExecuted applies equality check predicate on the "provider_executed" field. It's identical to ProviderExecutedEQ.
func ProviderExecuted(v bool) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldProviderExecuted, v))
}

// IsError applies equality check predicate on the "is_error" field. It's identical to IsErrorEQ.
func IsError(v bool) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldIsError, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldErrorMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldFinishedAt, v))
}

// StartOrder applies equality check predicate on the "start_order" field. It's identical to StartOrderEQ.
func StartOrder(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldStartOrder, v))
}

// EndOrder applies equality check predicate on the "end_order" field. It's identical to EndOrderEQ.
func EndOrder(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldEndOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotNull(FieldDeletedAt))
}

// TurnIDEQ applies the EQ predicate on the "turn_id" field.
func TurnIDEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldTurnID, v))
}

// TurnIDNEQ applies the NEQ predicate on the "turn_id" field.
func TurnIDNEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldTurnID, v))
}

// TurnIDIn applies the In predicate on the "turn_id" field.
func TurnIDIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldTurnID, vs...))
}

// TurnIDNotIn applies the NotIn predicate on the "turn_id" field.
func TurnIDNotIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldTurnID, vs...))
}

// TurnIDGT applies the GT predicate on the "turn_id" field.
func TurnIDGT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldTurnID, v))
}

// TurnIDGTE applies the GTE predicate on the "turn_id" field.
func TurnIDGTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldTurnID, v))
}

// TurnIDLT applies the LT predicate on the "turn_id" field.
func TurnIDLT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldTurnID, v))
}

// TurnIDLTE applies the LTE predicate on the "turn_id" field.
func TurnIDLTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldTurnID, v))
}

// TurnIDContains applies the Contains predicate on the "turn_id" field.
func TurnIDContains(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContains(FieldTurnID, v))
}

// TurnIDHasPrefix applies the HasPrefix predicate on the "turn_id" field.
func TurnIDHasPrefix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasPrefix(FieldTurnID, v))
}

// TurnIDHasSuffix applies the HasSuffix predicate on the "turn_id" field.
func TurnIDHasSuffix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasSuffix(FieldTurnID, v))
}

// TurnIDEqualFold applies the EqualFold predicate on the "turn_id" field.
func TurnIDEqualFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEqualFold(FieldTurnID, v))
}

// TurnIDContainsFold applies the ContainsFold predicate on the "turn_id" field.
func TurnIDContainsFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContainsFold(FieldTurnID, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldSequence, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldType, vs...))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContainsFold(FieldText, v))
}

// ToolCallIDEQ applies the EQ predicate on the "tool_call_id" field.
func ToolCallIDEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldToolCallID, v))
}

// ToolCallIDNEQ applies the NEQ predicate on the "tool_call_id" field.
func ToolCallIDNEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldToolCallID, v))
}

// ToolCallIDIn applies the In predicate on the "tool_call_id" field.
func ToolCallIDIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldToolCallID, vs...))
}

// ToolCallIDNotIn applies the NotIn predicate on the "tool_call_id" field.
func ToolCallIDNotIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldToolCallID, vs...))
}

// ToolCallIDGT applies the GT predicate on the "tool_call_id" field.
func ToolCallIDGT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldToolCallID, v))
}

// ToolCallIDGTE applies the GTE predicate on the "tool_call_id" field.
func ToolCallIDGTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldToolCallID, v))
}

// ToolCallIDLT applies the LT predicate on the "tool_call_id" field.
func ToolCallIDLT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldToolCallID, v))
}

// ToolCallIDLTE applies the LTE predicate on the "tool_call_id" field.
func ToolCallIDLTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldToolCallID, v))
}

// ToolCallIDContains applies the Contains predicate on the "tool_call_id" field.
func ToolCallIDContains(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContains(FieldToolCallID, v))
}

// ToolCallIDHasPrefix applies the HasPrefix predicate on the "tool_call_id" field.
func ToolCallIDHasPrefix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasPrefix(FieldToolCallID, v))
}

// ToolCallIDHasSuffix applies the HasSuffix predicate on the "tool_call_id" field.
func ToolCallIDHasSuffix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasSuffix(FieldToolCallID, v))
}

// ToolCallIDEqualFold applies the EqualFold predicate on the "tool_call_id" field.
func ToolCallIDEqualFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEqualFold(FieldToolCallID, v))
}

// ToolCallIDContainsFold applies the ContainsFold predicate on the "tool_call_id" field.
func ToolCallIDContainsFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContainsFold(FieldToolCallID, v))
}

// ToolNameEQ applies the EQ predicate on the "tool_name" field.
func ToolNameEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldToolName, v))
}

// ToolNameNEQ applies the NEQ predicate on the "tool_name" field.
func ToolNameNEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldToolName, v))
}

// ToolNameIn applies the In predicate on the "tool_name" field.
func ToolNameIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldToolName, vs...))
}

// ToolNameNotIn applies the NotIn predicate on the "tool_name" field.
func ToolNameNotIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldToolName, vs...))
}

// ToolNameGT applies the GT predicate on the "tool_name" field.
func ToolNameGT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldToolName, v))
}

// ToolNameGTE applies the GTE predicate on the "tool_name" field.
func ToolNameGTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldToolName, v))
}

// ToolNameLT applies the LT predicate on the "tool_name" field.
func ToolNameLT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldToolName, v))
}

// ToolNameLTE applies the LTE predicate on the "tool_name" field.
func ToolNameLTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldToolName, v))
}

// ToolNameContains applies the Contains predicate on the "tool_name" field.
func ToolNameContains(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContains(FieldToolName, v))
}

// ToolNameHasPrefix applies the HasPrefix predicate on the "tool_name" field.
func ToolNameHasPrefix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasPrefix(FieldToolName, v))
}

// ToolNameHasSuffix applies the HasSuffix predicate on the "tool_name" field.
func ToolNameHasSuffix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasSuffix(FieldToolName, v))
}

// ToolNameEqualFold applies the EqualFold predicate on the "tool_name" field.
func ToolNameEqualFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEqualFold(FieldToolName, v))
}

// ToolNameContainsFold applies the ContainsFold predicate on the "tool_name" field.
func ToolNameContainsFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContainsFold(FieldToolName, v))
}

// InputEQ applies the EQ predicate on the "input" field.
func InputEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldInput, v))
}

// InputNEQ applies the NEQ predicate on the "input" field.
func InputNEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldInput, v))
}

// InputIn applies the In predicate on the "input" field.
func InputIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldInput, vs...))
}

// InputNotIn applies the NotIn predicate on the "input" field.
func InputNotIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldInput, vs...))
}

// InputGT applies the GT predicate on the "input" field.
func InputGT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldInput, v))
}

// InputGTE applies the GTE predicate on the "input" field.
func InputGTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldInput, v))
}

// InputLT applies the LT predicate on the "input" field.
func InputLT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldInput, v))
}

// InputLTE applies the LTE predicate on the "input" field.
func InputLTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldInput, v))
}

// InputContains applies the Contains predicate on the "input" field.
func InputContains(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContains(FieldInput, v))
}

// InputHasPrefix applies the HasPrefix predicate on the "input" field.
func InputHasPrefix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasPrefix(FieldInput, v))
}

// InputHasSuffix applies the HasSuffix predicate on the "input" field.
func InputHasSuffix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasSuffix(FieldInput, v))
}

// InputEqualFold applies the EqualFold predicate on the "input" field.
func InputEqualFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEqualFold(FieldInput, v))
}

// InputContainsFold applies the ContainsFold predicate on the "input" field.
func InputContainsFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContainsFold(FieldInput, v))
}

// OutputIsNil applies the IsNil predicate on the "output" field.
func OutputIsNil() predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIsNull(FieldOutput))
}

// OutputNotNil applies the NotNil predicate on the "output" field.
func OutputNotNil() predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotNull(FieldOutput))
}

// ProviderExecutedEQ applies the EQ predicate on the "provider_executed" field.
func ProviderExecutedEQ(v bool) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldProviderExecuted, v))
}

// ProviderExecutedNEQ applies the NEQ predicate on the "provider_executed" field.
func ProviderExecutedNEQ(v bool) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldProviderExecuted, v))
}

// IsErrorEQ applies the EQ predicate on the "is_error" field.
func IsErrorEQ(v bool) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldIsError, v))
}

// IsErrorNEQ applies the NEQ predicate on the "is_error" field.
func IsErrorNEQ(v bool) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldIsError, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldFinishedAt, v))
}

// StartOrderEQ applies the EQ predicate on the "start_order" field.
func StartOrderEQ(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldStartOrder, v))
}

// StartOrderNEQ applies the NEQ predicate on the "start_order" field.
func StartOrderNEQ(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldStartOrder, v))
}

// StartOrderIn applies the In predicate on the "start_order" field.
func StartOrderIn(vs ...int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldStartOrder, vs...))
}

// StartOrderNotIn applies the NotIn predicate on the "start_order" field.
func StartOrderNotIn(vs ...int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldStartOrder, vs...))
}

// StartOrderGT applies the GT predicate on the "start_order" field.
func StartOrderGT(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldStartOrder, v))
}

// StartOrderGTE applies the GTE predicate on the "start_order" field.
func StartOrderGTE(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldStartOrder, v))
}

// StartOrderLT applies the LT predicate on the "start_order" field.
func StartOrderLT(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldStartOrder, v))
}

// StartOrderLTE applies the LTE predicate on the "start_order" field.
func StartOrderLTE(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldStartOrder, v))
}

// EndOrderEQ applies the EQ predicate on the "end_order" field.
func EndOrderEQ(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldEQ(FieldEndOrder, v))
}

// EndOrderNEQ applies the NEQ predicate on the "end_order" field.
func EndOrderNEQ(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNEQ(FieldEndOrder, v))
}

// EndOrderIn applies the In predicate on the "end_order" field.
func EndOrderIn(vs ...int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldIn(FieldEndOrder, vs...))
}

// EndOrderNotIn applies the NotIn predicate on the "end_order" field.
func EndOrderNotIn(vs ...int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldNotIn(FieldEndOrder, vs...))
}

// EndOrderGT applies the GT predicate on the "end_order" field.
func EndOrderGT(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGT(FieldEndOrder, v))
}

// EndOrderGTE applies the GTE predicate on the "end_order" field.
func EndOrderGTE(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldGTE(FieldEndOrder, v))
}

// EndOrderLT applies the LT predicate on the "end_order" field.
func EndOrderLT(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLT(FieldEndOrder, v))
}

// EndOrderLTE applies the LTE predicate on the "end_order" field.
func EndOrderLTE(v int64) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.FieldLTE(FieldEndOrder, v))
}

// HasTurn applies the HasEdge predicate on the "turn" edge.
func HasTurn() predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TurnTable, TurnColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTurnWith applies the HasEdge predicate on the "turn" edge with a given conditions (other predicates).
func HasTurnWith(preds ...predicate.KaguyaChatTurn) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(func(s *sql.Selector) {
		step := newTurnStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KaguyaChatBlock) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KaguyaChatBlock) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KaguyaChatBlock) predicate.KaguyaChatBlock {
	return predicate.KaguyaChatBlock(sql.NotPredicates(p))
}
