// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/kaguya/internal/dto/memory"
	"github.com/lyonmu/kaguya/internal/ent/kaguyamemoryrevision"
	"github.com/lyonmu/kaguya/internal/ent/predicate"
)

// KaguyaMemoryRevisionUpdate is the builder for updating KaguyaMemoryRevision entities.
type KaguyaMemoryRevisionUpdate struct {
	config
	hooks     []Hook
	mutation  *KaguyaMemoryRevisionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the KaguyaMemoryRevisionUpdate builder.
func (_u *KaguyaMemoryRevisionUpdate) Where(ps ...predicate.KaguyaMemoryRevision) *KaguyaMemoryRevisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KaguyaMemoryRevisionUpdate) SetUpdatedAt(v time.Time) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KaguyaMemoryRevisionUpdate) SetDeletedAt(v time.Time) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableDeletedAt(v *time.Time) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KaguyaMemoryRevisionUpdate) ClearDeletedAt() *KaguyaMemoryRevisionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPageID sets the "page_id" field.
func (_u *KaguyaMemoryRevisionUpdate) SetPageID(v string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetPageID(v)
	return _u
}

// SetNillablePageID sets the "page_id" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillablePageID(v *string) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetPageID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *KaguyaMemoryRevisionUpdate) SetVersion(v int64) *KaguyaMemoryRevisionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableVersion(v *int64) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *KaguyaMemoryRevisionUpdate) AddVersion(v int64) *KaguyaMemoryRevisionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCanonicalKey sets the "canonical_key" field.
func (_u *KaguyaMemoryRevisionUpdate) SetCanonicalKey(v string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetCanonicalKey(v)
	return _u
}

// SetNillableCanonicalKey sets the "canonical_key" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableCanonicalKey(v *string) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetCanonicalKey(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *KaguyaMemoryRevisionUpdate) SetKind(v kaguyamemoryrevision.Kind) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableKind(v *kaguyamemoryrevision.Kind) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *KaguyaMemoryRevisionUpdate) SetTitle(v string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableTitle(v *string) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *KaguyaMemoryRevisionUpdate) SetSummary(v string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableSummary(v *string) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *KaguyaMemoryRevisionUpdate) SetBody(v string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableBody(v *string) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetAliases sets the "aliases" field.
func (_u *KaguyaMemoryRevisionUpdate) SetAliases(v []string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetAliases(v)
	return _u
}

// AppendAliases appends value to the "aliases" field.
func (_u *KaguyaMemoryRevisionUpdate) AppendAliases(v []string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.AppendAliases(v)
	return _u
}

// ClearAliases clears the value of the "aliases" field.
func (_u *KaguyaMemoryRevisionUpdate) ClearAliases() *KaguyaMemoryRevisionUpdate {
	_u.mutation.ClearAliases()
	return _u
}

// SetStatus sets the "status" field.
func (_u *KaguyaMemoryRevisionUpdate) SetStatus(v kaguyamemoryrevision.Status) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableStatus(v *kaguyamemoryrevision.Status) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *KaguyaMemoryRevisionUpdate) SetPinned(v bool) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillablePinned(v *bool) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetUserLocked sets the "user_locked" field.
func (_u *KaguyaMemoryRevisionUpdate) SetUserLocked(v bool) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetUserLocked(v)
	return _u
}

// SetNillableUserLocked sets the "user_locked" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableUserLocked(v *bool) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetUserLocked(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *KaguyaMemoryRevisionUpdate) SetExpiresAt(v time.Time) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableExpiresAt(v *time.Time) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *KaguyaMemoryRevisionUpdate) ClearExpiresAt() *KaguyaMemoryRevisionUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetClaims sets the "claims" field.
func (_u *KaguyaMemoryRevisionUpdate) SetClaims(v []memory.MemoryClaim) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetClaims(v)
	return _u
}

// AppendClaims appends value to the "claims" field.
func (_u *KaguyaMemoryRevisionUpdate) AppendClaims(v []memory.MemoryClaim) *KaguyaMemoryRevisionUpdate {
	_u.mutation.AppendClaims(v)
	return _u
}

// ClearClaims clears the value of the "claims" field.
func (_u *KaguyaMemoryRevisionUpdate) ClearClaims() *KaguyaMemoryRevisionUpdate {
	_u.mutation.ClearClaims()
	return _u
}

// SetActor sets the "actor" field.
func (_u *KaguyaMemoryRevisionUpdate) SetActor(v kaguyamemoryrevision.Actor) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableActor(v *kaguyamemoryrevision.Actor) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *KaguyaMemoryRevisionUpdate) SetJobID(v string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableJobID(v *string) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *KaguyaMemoryRevisionUpdate) SetReason(v string) *KaguyaMemoryRevisionUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdate) SetNillableReason(v *string) *KaguyaMemoryRevisionUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// Mutation returns the KaguyaMemoryRevisionMutation object of the builder.
func (_u *KaguyaMemoryRevisionUpdate) Mutation() *KaguyaMemoryRevisionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KaguyaMemoryRevisionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KaguyaMemoryRevisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KaguyaMemoryRevisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KaguyaMemoryRevisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KaguyaMemoryRevisionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if kaguyamemoryrevision.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyamemoryrevision.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyamemoryrevision.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KaguyaMemoryRevisionUpdate) check() error {
	if v, ok := _u.mutation.PageID(); ok {
		if err := kaguyamemoryrevision.PageIDValidator(v); err != nil {
			return &ValidationError{Name: "page_id", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.page_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := kaguyamemoryrevision.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CanonicalKey(); ok {
		if err := kaguyamemoryrevision.CanonicalKeyValidator(v); err != nil {
			return &ValidationError{Name: "canonical_key", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.canonical_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := kaguyamemoryrevision.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := kaguyamemoryrevision.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := kaguyamemoryrevision.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Actor(); ok {
		if err := kaguyamemoryrevision.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.actor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JobID(); ok {
		if err := kaguyamemoryrevision.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.job_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KaguyaMemoryRevisionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KaguyaMemoryRevisionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KaguyaMemoryRevisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kaguyamemoryrevision.Table, kaguyamemoryrevision.Columns, sqlgraph.NewFieldSpec(kaguyamemoryrevision.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(kaguyamemoryrevision.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PageID(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldPageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(kaguyamemoryrevision.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CanonicalKey(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldCanonicalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Aliases(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldAliases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAliases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, kaguyamemoryrevision.FieldAliases, value)
		})
	}
	if _u.mutation.AliasesCleared() {
		_spec.ClearField(kaguyamemoryrevision.FieldAliases, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UserLocked(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldUserLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(kaguyamemoryrevision.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Claims(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldClaims, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedClaims(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, kaguyamemoryrevision.FieldClaims, value)
		})
	}
	if _u.mutation.ClaimsCleared() {
		_spec.ClearField(kaguyamemoryrevision.FieldClaims, field.TypeJSON)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldActor, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldJobID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldReason, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kaguyamemoryrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KaguyaMemoryRevisionUpdateOne is the builder for updating a single KaguyaMemoryRevision entity.
type KaguyaMemoryRevisionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *KaguyaMemoryRevisionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetUpdatedAt(v time.Time) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetDeletedAt(v time.Time) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableDeletedAt(v *time.Time) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KaguyaMemoryRevisionUpdateOne) ClearDeletedAt() *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPageID sets the "page_id" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetPageID(v string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetPageID(v)
	return _u
}

// SetNillablePageID sets the "page_id" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillablePageID(v *string) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetPageID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetVersion(v int64) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableVersion(v *int64) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *KaguyaMemoryRevisionUpdateOne) AddVersion(v int64) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCanonicalKey sets the "canonical_key" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetCanonicalKey(v string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetCanonicalKey(v)
	return _u
}

// SetNillableCanonicalKey sets the "canonical_key" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableCanonicalKey(v *string) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetCanonicalKey(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetKind(v kaguyamemoryrevision.Kind) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableKind(v *kaguyamemoryrevision.Kind) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetTitle(v string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableTitle(v *string) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetSummary(v string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableSummary(v *string) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetBody(v string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableBody(v *string) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetAliases sets the "aliases" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetAliases(v []string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetAliases(v)
	return _u
}

// AppendAliases appends value to the "aliases" field.
func (_u *KaguyaMemoryRevisionUpdateOne) AppendAliases(v []string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.AppendAliases(v)
	return _u
}

// ClearAliases clears the value of the "aliases" field.
func (_u *KaguyaMemoryRevisionUpdateOne) ClearAliases() *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.ClearAliases()
	return _u
}

// SetStatus sets the "status" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetStatus(v kaguyamemoryrevision.Status) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableStatus(v *kaguyamemoryrevision.Status) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetPinned(v bool) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillablePinned(v *bool) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetUserLocked sets the "user_locked" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetUserLocked(v bool) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetUserLocked(v)
	return _u
}

// SetNillableUserLocked sets the "user_locked" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableUserLocked(v *bool) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetUserLocked(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetExpiresAt(v time.Time) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableExpiresAt(v *time.Time) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *KaguyaMemoryRevisionUpdateOne) ClearExpiresAt() *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetClaims sets the "claims" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetClaims(v []memory.MemoryClaim) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetClaims(v)
	return _u
}

// AppendClaims appends value to the "claims" field.
func (_u *KaguyaMemoryRevisionUpdateOne) AppendClaims(v []memory.MemoryClaim) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.AppendClaims(v)
	return _u
}

// ClearClaims clears the value of the "claims" field.
func (_u *KaguyaMemoryRevisionUpdateOne) ClearClaims() *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.ClearClaims()
	return _u
}

// SetActor sets the "actor" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetActor(v kaguyamemoryrevision.Actor) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableActor(v *kaguyamemoryrevision.Actor) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetJobID(v string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableJobID(v *string) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *KaguyaMemoryRevisionUpdateOne) SetReason(v string) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *KaguyaMemoryRevisionUpdateOne) SetNillableReason(v *string) *KaguyaMemoryRevisionUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// Mutation returns the KaguyaMemoryRevisionMutation object of the builder.
func (_u *KaguyaMemoryRevisionUpdateOne) Mutation() *KaguyaMemoryRevisionMutation {
	return _u.mutation
}

// Where appends a list predicates to the KaguyaMemoryRevisionUpdate builder.
func (_u *KaguyaMemoryRevisionUpdateOne) Where(ps ...predicate.KaguyaMemoryRevision) *KaguyaMemoryRevisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KaguyaMemoryRevisionUpdateOne) Select(field string, fields ...string) *KaguyaMemoryRevisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KaguyaMemoryRevision entity.
func (_u *KaguyaMemoryRevisionUpdateOne) Save(ctx context.Context) (*KaguyaMemoryRevision, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KaguyaMemoryRevisionUpdateOne) SaveX(ctx context.Context) *KaguyaMemoryRevision {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KaguyaMemoryRevisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KaguyaMemoryRevisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KaguyaMemoryRevisionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if kaguyamemoryrevision.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyamemoryrevision.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyamemoryrevision.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KaguyaMemoryRevisionUpdateOne) check() error {
	if v, ok := _u.mutation.PageID(); ok {
		if err := kaguyamemoryrevision.PageIDValidator(v); err != nil {
			return &ValidationError{Name: "page_id", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.page_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := kaguyamemoryrevision.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CanonicalKey(); ok {
		if err := kaguyamemoryrevision.CanonicalKeyValidator(v); err != nil {
			return &ValidationError{Name: "canonical_key", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.canonical_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := kaguyamemoryrevision.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := kaguyamemoryrevision.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := kaguyamemoryrevision.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Actor(); ok {
		if err := kaguyamemoryrevision.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.actor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JobID(); ok {
		if err := kaguyamemoryrevision.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "KaguyaMemoryRevision.job_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KaguyaMemoryRevisionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KaguyaMemoryRevisionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KaguyaMemoryRevisionUpdateOne) sqlSave(ctx context.Context) (_node *KaguyaMemoryRevision, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kaguyamemoryrevision.Table, kaguyamemoryrevision.Columns, sqlgraph.NewFieldSpec(kaguyamemoryrevision.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KaguyaMemoryRevision.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kaguyamemoryrevision.FieldID)
		for _, f := range fields {
			if !kaguyamemoryrevision.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kaguyamemoryrevision.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(kaguyamemoryrevision.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PageID(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldPageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(kaguyamemoryrevision.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CanonicalKey(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldCanonicalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Aliases(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldAliases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAliases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, kaguyamemoryrevision.FieldAliases, value)
		})
	}
	if _u.mutation.AliasesCleared() {
		_spec.ClearField(kaguyamemoryrevision.FieldAliases, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UserLocked(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldUserLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(kaguyamemoryrevision.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Claims(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldClaims, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedClaims(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, kaguyamemoryrevision.FieldClaims, value)
		})
	}
	if _u.mutation.ClaimsCleared() {
		_spec.ClearField(kaguyamemoryrevision.FieldClaims, field.TypeJSON)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldActor, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldJobID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(kaguyamemoryrevision.FieldReason, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &KaguyaMemoryRevision{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kaguyamemoryrevision.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
