// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/kaguya/internal/ent/kaguyasysteminfo"
	"github.com/lyonmu/kaguya/internal/ent/predicate"
)

// KaguyaSystemInfoUpdate is the builder for updating KaguyaSystemInfo entities.
type KaguyaSystemInfoUpdate struct {
	config
	hooks     []Hook
	mutation  *KaguyaSystemInfoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the KaguyaSystemInfoUpdate builder.
func (_u *KaguyaSystemInfoUpdate) Where(ps ...predicate.KaguyaSystemInfo) *KaguyaSystemInfoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KaguyaSystemInfoUpdate) SetUpdatedAt(v time.Time) *KaguyaSystemInfoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KaguyaSystemInfoUpdate) SetDeletedAt(v time.Time) *KaguyaSystemInfoUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableDeletedAt(v *time.Time) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KaguyaSystemInfoUpdate) ClearDeletedAt() *KaguyaSystemInfoUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetAgentMaxSteps sets the "agent_max_steps" field.
func (_u *KaguyaSystemInfoUpdate) SetAgentMaxSteps(v int) *KaguyaSystemInfoUpdate {
	_u.mutation.ResetAgentMaxSteps()
	_u.mutation.SetAgentMaxSteps(v)
	return _u
}

// SetNillableAgentMaxSteps sets the "agent_max_steps" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableAgentMaxSteps(v *int) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetAgentMaxSteps(*v)
	}
	return _u
}

// AddAgentMaxSteps adds value to the "agent_max_steps" field.
func (_u *KaguyaSystemInfoUpdate) AddAgentMaxSteps(v int) *KaguyaSystemInfoUpdate {
	_u.mutation.AddAgentMaxSteps(v)
	return _u
}

// SetContextCompactionPercent sets the "context_compaction_percent" field.
func (_u *KaguyaSystemInfoUpdate) SetContextCompactionPercent(v int) *KaguyaSystemInfoUpdate {
	_u.mutation.ResetContextCompactionPercent()
	_u.mutation.SetContextCompactionPercent(v)
	return _u
}

// SetNillableContextCompactionPercent sets the "context_compaction_percent" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableContextCompactionPercent(v *int) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetContextCompactionPercent(*v)
	}
	return _u
}

// AddContextCompactionPercent adds value to the "context_compaction_percent" field.
func (_u *KaguyaSystemInfoUpdate) AddContextCompactionPercent(v int) *KaguyaSystemInfoUpdate {
	_u.mutation.AddContextCompactionPercent(v)
	return _u
}

// SetTLSCertificatePem sets the "tls_certificate_pem" field.
func (_u *KaguyaSystemInfoUpdate) SetTLSCertificatePem(v string) *KaguyaSystemInfoUpdate {
	_u.mutation.SetTLSCertificatePem(v)
	return _u
}

// SetNillableTLSCertificatePem sets the "tls_certificate_pem" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableTLSCertificatePem(v *string) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetTLSCertificatePem(*v)
	}
	return _u
}

// SetTLSPrivateKeyPem sets the "tls_private_key_pem" field.
func (_u *KaguyaSystemInfoUpdate) SetTLSPrivateKeyPem(v string) *KaguyaSystemInfoUpdate {
	_u.mutation.SetTLSPrivateKeyPem(v)
	return _u
}

// SetNillableTLSPrivateKeyPem sets the "tls_private_key_pem" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableTLSPrivateKeyPem(v *string) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetTLSPrivateKeyPem(*v)
	}
	return _u
}

// SetCommandTimeoutSeconds sets the "command_timeout_seconds" field.
func (_u *KaguyaSystemInfoUpdate) SetCommandTimeoutSeconds(v int) *KaguyaSystemInfoUpdate {
	_u.mutation.ResetCommandTimeoutSeconds()
	_u.mutation.SetCommandTimeoutSeconds(v)
	return _u
}

// SetNillableCommandTimeoutSeconds sets the "command_timeout_seconds" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableCommandTimeoutSeconds(v *int) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetCommandTimeoutSeconds(*v)
	}
	return _u
}

// AddCommandTimeoutSeconds adds value to the "command_timeout_seconds" field.
func (_u *KaguyaSystemInfoUpdate) AddCommandTimeoutSeconds(v int) *KaguyaSystemInfoUpdate {
	_u.mutation.AddCommandTimeoutSeconds(v)
	return _u
}

// SetChatMaxRetries sets the "chat_max_retries" field.
func (_u *KaguyaSystemInfoUpdate) SetChatMaxRetries(v int) *KaguyaSystemInfoUpdate {
	_u.mutation.ResetChatMaxRetries()
	_u.mutation.SetChatMaxRetries(v)
	return _u
}

// SetNillableChatMaxRetries sets the "chat_max_retries" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableChatMaxRetries(v *int) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetChatMaxRetries(*v)
	}
	return _u
}

// AddChatMaxRetries adds value to the "chat_max_retries" field.
func (_u *KaguyaSystemInfoUpdate) AddChatMaxRetries(v int) *KaguyaSystemInfoUpdate {
	_u.mutation.AddChatMaxRetries(v)
	return _u
}

// SetGlobalAgentsPaths sets the "global_agents_paths" field.
func (_u *KaguyaSystemInfoUpdate) SetGlobalAgentsPaths(v []string) *KaguyaSystemInfoUpdate {
	_u.mutation.SetGlobalAgentsPaths(v)
	return _u
}

// AppendGlobalAgentsPaths appends value to the "global_agents_paths" field.
func (_u *KaguyaSystemInfoUpdate) AppendGlobalAgentsPaths(v []string) *KaguyaSystemInfoUpdate {
	_u.mutation.AppendGlobalAgentsPaths(v)
	return _u
}

// ClearGlobalAgentsPaths clears the value of the "global_agents_paths" field.
func (_u *KaguyaSystemInfoUpdate) ClearGlobalAgentsPaths() *KaguyaSystemInfoUpdate {
	_u.mutation.ClearGlobalAgentsPaths()
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *KaguyaSystemInfoUpdate) SetSystemPrompt(v string) *KaguyaSystemInfoUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableSystemPrompt(v *string) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *KaguyaSystemInfoUpdate) SetUserAgent(v string) *KaguyaSystemInfoUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableUserAgent(v *string) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetDefaultModelID sets the "default_model_id" field.
func (_u *KaguyaSystemInfoUpdate) SetDefaultModelID(v string) *KaguyaSystemInfoUpdate {
	_u.mutation.SetDefaultModelID(v)
	return _u
}

// SetNillableDefaultModelID sets the "default_model_id" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableDefaultModelID(v *string) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetDefaultModelID(*v)
	}
	return _u
}

// SetTaskModelID sets the "task_model_id" field.
func (_u *KaguyaSystemInfoUpdate) SetTaskModelID(v string) *KaguyaSystemInfoUpdate {
	_u.mutation.SetTaskModelID(v)
	return _u
}

// SetNillableTaskModelID sets the "task_model_id" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdate) SetNillableTaskModelID(v *string) *KaguyaSystemInfoUpdate {
	if v != nil {
		_u.SetTaskModelID(*v)
	}
	return _u
}

// Mutation returns the KaguyaSystemInfoMutation object of the builder.
func (_u *KaguyaSystemInfoUpdate) Mutation() *KaguyaSystemInfoMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KaguyaSystemInfoUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KaguyaSystemInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KaguyaSystemInfoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KaguyaSystemInfoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KaguyaSystemInfoUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if kaguyasysteminfo.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyasysteminfo.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyasysteminfo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KaguyaSystemInfoUpdate) check() error {
	if v, ok := _u.mutation.AgentMaxSteps(); ok {
		if err := kaguyasysteminfo.AgentMaxStepsValidator(v); err != nil {
			return &ValidationError{Name: "agent_max_steps", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.agent_max_steps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContextCompactionPercent(); ok {
		if err := kaguyasysteminfo.ContextCompactionPercentValidator(v); err != nil {
			return &ValidationError{Name: "context_compaction_percent", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.context_compaction_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommandTimeoutSeconds(); ok {
		if err := kaguyasysteminfo.CommandTimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "command_timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.command_timeout_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatMaxRetries(); ok {
		if err := kaguyasysteminfo.ChatMaxRetriesValidator(v); err != nil {
			return &ValidationError{Name: "chat_max_retries", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.chat_max_retries": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := kaguyasysteminfo.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.user_agent": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KaguyaSystemInfoUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KaguyaSystemInfoUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KaguyaSystemInfoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kaguyasysteminfo.Table, kaguyasysteminfo.Columns, sqlgraph.NewFieldSpec(kaguyasysteminfo.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyasysteminfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyasysteminfo.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(kaguyasysteminfo.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AgentMaxSteps(); ok {
		_spec.SetField(kaguyasysteminfo.FieldAgentMaxSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAgentMaxSteps(); ok {
		_spec.AddField(kaguyasysteminfo.FieldAgentMaxSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContextCompactionPercent(); ok {
		_spec.SetField(kaguyasysteminfo.FieldContextCompactionPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContextCompactionPercent(); ok {
		_spec.AddField(kaguyasysteminfo.FieldContextCompactionPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TLSCertificatePem(); ok {
		_spec.SetField(kaguyasysteminfo.FieldTLSCertificatePem, field.TypeString, value)
	}
	if value, ok := _u.mutation.TLSPrivateKeyPem(); ok {
		_spec.SetField(kaguyasysteminfo.FieldTLSPrivateKeyPem, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommandTimeoutSeconds(); ok {
		_spec.SetField(kaguyasysteminfo.FieldCommandTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommandTimeoutSeconds(); ok {
		_spec.AddField(kaguyasysteminfo.FieldCommandTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChatMaxRetries(); ok {
		_spec.SetField(kaguyasysteminfo.FieldChatMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChatMaxRetries(); ok {
		_spec.AddField(kaguyasysteminfo.FieldChatMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GlobalAgentsPaths(); ok {
		_spec.SetField(kaguyasysteminfo.FieldGlobalAgentsPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGlobalAgentsPaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, kaguyasysteminfo.FieldGlobalAgentsPaths, value)
		})
	}
	if _u.mutation.GlobalAgentsPathsCleared() {
		_spec.ClearField(kaguyasysteminfo.FieldGlobalAgentsPaths, field.TypeJSON)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(kaguyasysteminfo.FieldSystemPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(kaguyasysteminfo.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultModelID(); ok {
		_spec.SetField(kaguyasysteminfo.FieldDefaultModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskModelID(); ok {
		_spec.SetField(kaguyasysteminfo.FieldTaskModelID, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kaguyasysteminfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KaguyaSystemInfoUpdateOne is the builder for updating a single KaguyaSystemInfo entity.
type KaguyaSystemInfoUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *KaguyaSystemInfoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KaguyaSystemInfoUpdateOne) SetUpdatedAt(v time.Time) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KaguyaSystemInfoUpdateOne) SetDeletedAt(v time.Time) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableDeletedAt(v *time.Time) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KaguyaSystemInfoUpdateOne) ClearDeletedAt() *KaguyaSystemInfoUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetAgentMaxSteps sets the "agent_max_steps" field.
func (_u *KaguyaSystemInfoUpdateOne) SetAgentMaxSteps(v int) *KaguyaSystemInfoUpdateOne {
	_u.mutation.ResetAgentMaxSteps()
	_u.mutation.SetAgentMaxSteps(v)
	return _u
}

// SetNillableAgentMaxSteps sets the "agent_max_steps" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableAgentMaxSteps(v *int) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetAgentMaxSteps(*v)
	}
	return _u
}

// AddAgentMaxSteps adds value to the "agent_max_steps" field.
func (_u *KaguyaSystemInfoUpdateOne) AddAgentMaxSteps(v int) *KaguyaSystemInfoUpdateOne {
	_u.mutation.AddAgentMaxSteps(v)
	return _u
}

// SetContextCompactionPercent sets the "context_compaction_percent" field.
func (_u *KaguyaSystemInfoUpdateOne) SetContextCompactionPercent(v int) *KaguyaSystemInfoUpdateOne {
	_u.mutation.ResetContextCompactionPercent()
	_u.mutation.SetContextCompactionPercent(v)
	return _u
}

// SetNillableContextCompactionPercent sets the "context_compaction_percent" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableContextCompactionPercent(v *int) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetContextCompactionPercent(*v)
	}
	return _u
}

// AddContextCompactionPercent adds value to the "context_compaction_percent" field.
func (_u *KaguyaSystemInfoUpdateOne) AddContextCompactionPercent(v int) *KaguyaSystemInfoUpdateOne {
	_u.mutation.AddContextCompactionPercent(v)
	return _u
}

// SetTLSCertificatePem sets the "tls_certificate_pem" field.
func (_u *KaguyaSystemInfoUpdateOne) SetTLSCertificatePem(v string) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetTLSCertificatePem(v)
	return _u
}

// SetNillableTLSCertificatePem sets the "tls_certificate_pem" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableTLSCertificatePem(v *string) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetTLSCertificatePem(*v)
	}
	return _u
}

// SetTLSPrivateKeyPem sets the "tls_private_key_pem" field.
func (_u *KaguyaSystemInfoUpdateOne) SetTLSPrivateKeyPem(v string) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetTLSPrivateKeyPem(v)
	return _u
}

// SetNillableTLSPrivateKeyPem sets the "tls_private_key_pem" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableTLSPrivateKeyPem(v *string) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetTLSPrivateKeyPem(*v)
	}
	return _u
}

// SetCommandTimeoutSeconds sets the "command_timeout_seconds" field.
func (_u *KaguyaSystemInfoUpdateOne) SetCommandTimeoutSeconds(v int) *KaguyaSystemInfoUpdateOne {
	_u.mutation.ResetCommandTimeoutSeconds()
	_u.mutation.SetCommandTimeoutSeconds(v)
	return _u
}

// SetNillableCommandTimeoutSeconds sets the "command_timeout_seconds" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableCommandTimeoutSeconds(v *int) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetCommandTimeoutSeconds(*v)
	}
	return _u
}

// AddCommandTimeoutSeconds adds value to the "command_timeout_seconds" field.
func (_u *KaguyaSystemInfoUpdateOne) AddCommandTimeoutSeconds(v int) *KaguyaSystemInfoUpdateOne {
	_u.mutation.AddCommandTimeoutSeconds(v)
	return _u
}

// SetChatMaxRetries sets the "chat_max_retries" field.
func (_u *KaguyaSystemInfoUpdateOne) SetChatMaxRetries(v int) *KaguyaSystemInfoUpdateOne {
	_u.mutation.ResetChatMaxRetries()
	_u.mutation.SetChatMaxRetries(v)
	return _u
}

// SetNillableChatMaxRetries sets the "chat_max_retries" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableChatMaxRetries(v *int) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetChatMaxRetries(*v)
	}
	return _u
}

// AddChatMaxRetries adds value to the "chat_max_retries" field.
func (_u *KaguyaSystemInfoUpdateOne) AddChatMaxRetries(v int) *KaguyaSystemInfoUpdateOne {
	_u.mutation.AddChatMaxRetries(v)
	return _u
}

// SetGlobalAgentsPaths sets the "global_agents_paths" field.
func (_u *KaguyaSystemInfoUpdateOne) SetGlobalAgentsPaths(v []string) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetGlobalAgentsPaths(v)
	return _u
}

// AppendGlobalAgentsPaths appends value to the "global_agents_paths" field.
func (_u *KaguyaSystemInfoUpdateOne) AppendGlobalAgentsPaths(v []string) *KaguyaSystemInfoUpdateOne {
	_u.mutation.AppendGlobalAgentsPaths(v)
	return _u
}

// ClearGlobalAgentsPaths clears the value of the "global_agents_paths" field.
func (_u *KaguyaSystemInfoUpdateOne) ClearGlobalAgentsPaths() *KaguyaSystemInfoUpdateOne {
	_u.mutation.ClearGlobalAgentsPaths()
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *KaguyaSystemInfoUpdateOne) SetSystemPrompt(v string) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableSystemPrompt(v *string) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *KaguyaSystemInfoUpdateOne) SetUserAgent(v string) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableUserAgent(v *string) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetDefaultModelID sets the "default_model_id" field.
func (_u *KaguyaSystemInfoUpdateOne) SetDefaultModelID(v string) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetDefaultModelID(v)
	return _u
}

// SetNillableDefaultModelID sets the "default_model_id" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableDefaultModelID(v *string) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetDefaultModelID(*v)
	}
	return _u
}

// SetTaskModelID sets the "task_model_id" field.
func (_u *KaguyaSystemInfoUpdateOne) SetTaskModelID(v string) *KaguyaSystemInfoUpdateOne {
	_u.mutation.SetTaskModelID(v)
	return _u
}

// SetNillableTaskModelID sets the "task_model_id" field if the given value is not nil.
func (_u *KaguyaSystemInfoUpdateOne) SetNillableTaskModelID(v *string) *KaguyaSystemInfoUpdateOne {
	if v != nil {
		_u.SetTaskModelID(*v)
	}
	return _u
}

// Mutation returns the KaguyaSystemInfoMutation object of the builder.
func (_u *KaguyaSystemInfoUpdateOne) Mutation() *KaguyaSystemInfoMutation {
	return _u.mutation
}

// Where appends a list predicates to the KaguyaSystemInfoUpdate builder.
func (_u *KaguyaSystemInfoUpdateOne) Where(ps ...predicate.KaguyaSystemInfo) *KaguyaSystemInfoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KaguyaSystemInfoUpdateOne) Select(field string, fields ...string) *KaguyaSystemInfoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KaguyaSystemInfo entity.
func (_u *KaguyaSystemInfoUpdateOne) Save(ctx context.Context) (*KaguyaSystemInfo, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KaguyaSystemInfoUpdateOne) SaveX(ctx context.Context) *KaguyaSystemInfo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KaguyaSystemInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KaguyaSystemInfoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KaguyaSystemInfoUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if kaguyasysteminfo.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyasysteminfo.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyasysteminfo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KaguyaSystemInfoUpdateOne) check() error {
	if v, ok := _u.mutation.AgentMaxSteps(); ok {
		if err := kaguyasysteminfo.AgentMaxStepsValidator(v); err != nil {
			return &ValidationError{Name: "agent_max_steps", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.agent_max_steps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContextCompactionPercent(); ok {
		if err := kaguyasysteminfo.ContextCompactionPercentValidator(v); err != nil {
			return &ValidationError{Name: "context_compaction_percent", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.context_compaction_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CommandTimeoutSeconds(); ok {
		if err := kaguyasysteminfo.CommandTimeoutSecondsValidator(v); err != nil {
			return &ValidationError{Name: "command_timeout_seconds", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.command_timeout_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatMaxRetries(); ok {
		if err := kaguyasysteminfo.ChatMaxRetriesValidator(v); err != nil {
			return &ValidationError{Name: "chat_max_retries", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.chat_max_retries": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := kaguyasysteminfo.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "KaguyaSystemInfo.user_agent": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KaguyaSystemInfoUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KaguyaSystemInfoUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KaguyaSystemInfoUpdateOne) sqlSave(ctx context.Context) (_node *KaguyaSystemInfo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kaguyasysteminfo.Table, kaguyasysteminfo.Columns, sqlgraph.NewFieldSpec(kaguyasysteminfo.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KaguyaSystemInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kaguyasysteminfo.FieldID)
		for _, f := range fields {
			if !kaguyasysteminfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kaguyasysteminfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyasysteminfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyasysteminfo.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(kaguyasysteminfo.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AgentMaxSteps(); ok {
		_spec.SetField(kaguyasysteminfo.FieldAgentMaxSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAgentMaxSteps(); ok {
		_spec.AddField(kaguyasysteminfo.FieldAgentMaxSteps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContextCompactionPercent(); ok {
		_spec.SetField(kaguyasysteminfo.FieldContextCompactionPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContextCompactionPercent(); ok {
		_spec.AddField(kaguyasysteminfo.FieldContextCompactionPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TLSCertificatePem(); ok {
		_spec.SetField(kaguyasysteminfo.FieldTLSCertificatePem, field.TypeString, value)
	}
	if value, ok := _u.mutation.TLSPrivateKeyPem(); ok {
		_spec.SetField(kaguyasysteminfo.FieldTLSPrivateKeyPem, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommandTimeoutSeconds(); ok {
		_spec.SetField(kaguyasysteminfo.FieldCommandTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommandTimeoutSeconds(); ok {
		_spec.AddField(kaguyasysteminfo.FieldCommandTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChatMaxRetries(); ok {
		_spec.SetField(kaguyasysteminfo.FieldChatMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChatMaxRetries(); ok {
		_spec.AddField(kaguyasysteminfo.FieldChatMaxRetries, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GlobalAgentsPaths(); ok {
		_spec.SetField(kaguyasysteminfo.FieldGlobalAgentsPaths, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGlobalAgentsPaths(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, kaguyasysteminfo.FieldGlobalAgentsPaths, value)
		})
	}
	if _u.mutation.GlobalAgentsPathsCleared() {
		_spec.ClearField(kaguyasysteminfo.FieldGlobalAgentsPaths, field.TypeJSON)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(kaguyasysteminfo.FieldSystemPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(kaguyasysteminfo.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultModelID(); ok {
		_spec.SetField(kaguyasysteminfo.FieldDefaultModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskModelID(); ok {
		_spec.SetField(kaguyasysteminfo.FieldTaskModelID, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &KaguyaSystemInfo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kaguyasysteminfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
