// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/kaguya/internal/ent/kaguyataskusage"
	"github.com/lyonmu/kaguya/internal/ent/predicate"
)

// KaguyaTaskUsageUpdate is the builder for updating KaguyaTaskUsage entities.
type KaguyaTaskUsageUpdate struct {
	config
	hooks     []Hook
	mutation  *KaguyaTaskUsageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the KaguyaTaskUsageUpdate builder.
func (_u *KaguyaTaskUsageUpdate) Where(ps ...predicate.KaguyaTaskUsage) *KaguyaTaskUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KaguyaTaskUsageUpdate) SetUpdatedAt(v time.Time) *KaguyaTaskUsageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KaguyaTaskUsageUpdate) SetDeletedAt(v time.Time) *KaguyaTaskUsageUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableDeletedAt(v *time.Time) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KaguyaTaskUsageUpdate) ClearDeletedAt() *KaguyaTaskUsageUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetKind sets the "kind" field.
func (_u *KaguyaTaskUsageUpdate) SetKind(v string) *KaguyaTaskUsageUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableKind(v *string) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *KaguyaTaskUsageUpdate) SetConversationID(v string) *KaguyaTaskUsageUpdate {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableConversationID(v *string) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *KaguyaTaskUsageUpdate) SetProviderID(v string) *KaguyaTaskUsageUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableProviderID(v *string) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetProviderName sets the "provider_name" field.
func (_u *KaguyaTaskUsageUpdate) SetProviderName(v string) *KaguyaTaskUsageUpdate {
	_u.mutation.SetProviderName(v)
	return _u
}

// SetNillableProviderName sets the "provider_name" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableProviderName(v *string) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetProviderName(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *KaguyaTaskUsageUpdate) SetModelID(v string) *KaguyaTaskUsageUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableModelID(v *string) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *KaguyaTaskUsageUpdate) SetModelName(v string) *KaguyaTaskUsageUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableModelName(v *string) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *KaguyaTaskUsageUpdate) SetFinishedAt(v time.Time) *KaguyaTaskUsageUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableFinishedAt(v *time.Time) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// SetUsageKnown sets the "usage_known" field.
func (_u *KaguyaTaskUsageUpdate) SetUsageKnown(v bool) *KaguyaTaskUsageUpdate {
	_u.mutation.SetUsageKnown(v)
	return _u
}

// SetNillableUsageKnown sets the "usage_known" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableUsageKnown(v *bool) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetUsageKnown(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *KaguyaTaskUsageUpdate) SetInputTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableInputTokens(v *int64) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *KaguyaTaskUsageUpdate) AddInputTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *KaguyaTaskUsageUpdate) SetOutputTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableOutputTokens(v *int64) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *KaguyaTaskUsageUpdate) AddOutputTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_u *KaguyaTaskUsageUpdate) SetReasoningTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.ResetReasoningTokens()
	_u.mutation.SetReasoningTokens(v)
	return _u
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableReasoningTokens(v *int64) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetReasoningTokens(*v)
	}
	return _u
}

// AddReasoningTokens adds value to the "reasoning_tokens" field.
func (_u *KaguyaTaskUsageUpdate) AddReasoningTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.AddReasoningTokens(v)
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *KaguyaTaskUsageUpdate) SetCachedTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableCachedTokens(v *int64) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *KaguyaTaskUsageUpdate) AddCachedTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *KaguyaTaskUsageUpdate) SetTotalTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdate) SetNillableTotalTokens(v *int64) *KaguyaTaskUsageUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *KaguyaTaskUsageUpdate) AddTotalTokens(v int64) *KaguyaTaskUsageUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// Mutation returns the KaguyaTaskUsageMutation object of the builder.
func (_u *KaguyaTaskUsageUpdate) Mutation() *KaguyaTaskUsageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KaguyaTaskUsageUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KaguyaTaskUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KaguyaTaskUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KaguyaTaskUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KaguyaTaskUsageUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if kaguyataskusage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyataskusage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyataskusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KaguyaTaskUsageUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := kaguyataskusage.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputTokens(); ok {
		if err := kaguyataskusage.InputTokensValidator(v); err != nil {
			return &ValidationError{Name: "input_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.input_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputTokens(); ok {
		if err := kaguyataskusage.OutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "output_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.output_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReasoningTokens(); ok {
		if err := kaguyataskusage.ReasoningTokensValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.reasoning_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CachedTokens(); ok {
		if err := kaguyataskusage.CachedTokensValidator(v); err != nil {
			return &ValidationError{Name: "cached_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.cached_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalTokens(); ok {
		if err := kaguyataskusage.TotalTokensValidator(v); err != nil {
			return &ValidationError{Name: "total_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.total_tokens": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KaguyaTaskUsageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KaguyaTaskUsageUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KaguyaTaskUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kaguyataskusage.Table, kaguyataskusage.Columns, sqlgraph.NewFieldSpec(kaguyataskusage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyataskusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyataskusage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(kaguyataskusage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(kaguyataskusage.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(kaguyataskusage.FieldConversationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(kaguyataskusage.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderName(); ok {
		_spec.SetField(kaguyataskusage.FieldProviderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(kaguyataskusage.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(kaguyataskusage.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(kaguyataskusage.FieldFinishedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsageKnown(); ok {
		_spec.SetField(kaguyataskusage.FieldUsageKnown, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReasoningTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReasoningTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldTotalTokens, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kaguyataskusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KaguyaTaskUsageUpdateOne is the builder for updating a single KaguyaTaskUsage entity.
type KaguyaTaskUsageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *KaguyaTaskUsageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KaguyaTaskUsageUpdateOne) SetUpdatedAt(v time.Time) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KaguyaTaskUsageUpdateOne) SetDeletedAt(v time.Time) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableDeletedAt(v *time.Time) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KaguyaTaskUsageUpdateOne) ClearDeletedAt() *KaguyaTaskUsageUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetKind sets the "kind" field.
func (_u *KaguyaTaskUsageUpdateOne) SetKind(v string) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableKind(v *string) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *KaguyaTaskUsageUpdateOne) SetConversationID(v string) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableConversationID(v *string) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *KaguyaTaskUsageUpdateOne) SetProviderID(v string) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableProviderID(v *string) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetProviderName sets the "provider_name" field.
func (_u *KaguyaTaskUsageUpdateOne) SetProviderName(v string) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetProviderName(v)
	return _u
}

// SetNillableProviderName sets the "provider_name" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableProviderName(v *string) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetProviderName(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *KaguyaTaskUsageUpdateOne) SetModelID(v string) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableModelID(v *string) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *KaguyaTaskUsageUpdateOne) SetModelName(v string) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableModelName(v *string) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *KaguyaTaskUsageUpdateOne) SetFinishedAt(v time.Time) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableFinishedAt(v *time.Time) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// SetUsageKnown sets the "usage_known" field.
func (_u *KaguyaTaskUsageUpdateOne) SetUsageKnown(v bool) *KaguyaTaskUsageUpdateOne {
	_u.mutation.SetUsageKnown(v)
	return _u
}

// SetNillableUsageKnown sets the "usage_known" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableUsageKnown(v *bool) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetUsageKnown(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) SetInputTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableInputTokens(v *int64) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) AddInputTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) SetOutputTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableOutputTokens(v *int64) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) AddOutputTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) SetReasoningTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.ResetReasoningTokens()
	_u.mutation.SetReasoningTokens(v)
	return _u
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableReasoningTokens(v *int64) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetReasoningTokens(*v)
	}
	return _u
}

// AddReasoningTokens adds value to the "reasoning_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) AddReasoningTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.AddReasoningTokens(v)
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) SetCachedTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableCachedTokens(v *int64) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) AddCachedTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) SetTotalTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *KaguyaTaskUsageUpdateOne) SetNillableTotalTokens(v *int64) *KaguyaTaskUsageUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *KaguyaTaskUsageUpdateOne) AddTotalTokens(v int64) *KaguyaTaskUsageUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// Mutation returns the KaguyaTaskUsageMutation object of the builder.
func (_u *KaguyaTaskUsageUpdateOne) Mutation() *KaguyaTaskUsageMutation {
	return _u.mutation
}

// Where appends a list predicates to the KaguyaTaskUsageUpdate builder.
func (_u *KaguyaTaskUsageUpdateOne) Where(ps ...predicate.KaguyaTaskUsage) *KaguyaTaskUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KaguyaTaskUsageUpdateOne) Select(field string, fields ...string) *KaguyaTaskUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KaguyaTaskUsage entity.
func (_u *KaguyaTaskUsageUpdateOne) Save(ctx context.Context) (*KaguyaTaskUsage, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KaguyaTaskUsageUpdateOne) SaveX(ctx context.Context) *KaguyaTaskUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KaguyaTaskUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KaguyaTaskUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KaguyaTaskUsageUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if kaguyataskusage.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyataskusage.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyataskusage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KaguyaTaskUsageUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := kaguyataskusage.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputTokens(); ok {
		if err := kaguyataskusage.InputTokensValidator(v); err != nil {
			return &ValidationError{Name: "input_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.input_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputTokens(); ok {
		if err := kaguyataskusage.OutputTokensValidator(v); err != nil {
			return &ValidationError{Name: "output_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.output_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReasoningTokens(); ok {
		if err := kaguyataskusage.ReasoningTokensValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.reasoning_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CachedTokens(); ok {
		if err := kaguyataskusage.CachedTokensValidator(v); err != nil {
			return &ValidationError{Name: "cached_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.cached_tokens": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalTokens(); ok {
		if err := kaguyataskusage.TotalTokensValidator(v); err != nil {
			return &ValidationError{Name: "total_tokens", err: fmt.Errorf(`ent: validator failed for field "KaguyaTaskUsage.total_tokens": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KaguyaTaskUsageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KaguyaTaskUsageUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KaguyaTaskUsageUpdateOne) sqlSave(ctx context.Context) (_node *KaguyaTaskUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kaguyataskusage.Table, kaguyataskusage.Columns, sqlgraph.NewFieldSpec(kaguyataskusage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KaguyaTaskUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kaguyataskusage.FieldID)
		for _, f := range fields {
			if !kaguyataskusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kaguyataskusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyataskusage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyataskusage.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(kaguyataskusage.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(kaguyataskusage.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(kaguyataskusage.FieldConversationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(kaguyataskusage.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderName(); ok {
		_spec.SetField(kaguyataskusage.FieldProviderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(kaguyataskusage.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(kaguyataskusage.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(kaguyataskusage.FieldFinishedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsageKnown(); ok {
		_spec.SetField(kaguyataskusage.FieldUsageKnown, field.TypeBool, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReasoningTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReasoningTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(kaguyataskusage.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(kaguyataskusage.FieldTotalTokens, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &KaguyaTaskUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kaguyataskusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
