// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/kaguya/internal/ent/kaguyachatturn"
	"github.com/lyonmu/kaguya/internal/ent/kaguyaconversation"
	"github.com/lyonmu/kaguya/internal/ent/kaguyaproject"
	"github.com/lyonmu/kaguya/internal/ent/predicate"
)

// KaguyaConversationQuery is the builder for querying KaguyaConversation entities.
type KaguyaConversationQuery struct {
	config
	ctx         *QueryContext
	order       []kaguyaconversation.OrderOption
	inters      []Interceptor
	predicates  []predicate.KaguyaConversation
	withTurns   *KaguyaChatTurnQuery
	withProject *KaguyaProjectQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the KaguyaConversationQuery builder.
func (_q *KaguyaConversationQuery) Where(ps ...predicate.KaguyaConversation) *KaguyaConversationQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *KaguyaConversationQuery) Limit(limit int) *KaguyaConversationQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *KaguyaConversationQuery) Offset(offset int) *KaguyaConversationQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *KaguyaConversationQuery) Unique(unique bool) *KaguyaConversationQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *KaguyaConversationQuery) Order(o ...kaguyaconversation.OrderOption) *KaguyaConversationQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTurns chains the current query on the "turns" edge.
func (_q *KaguyaConversationQuery) QueryTurns() *KaguyaChatTurnQuery {
	query := (&KaguyaChatTurnClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(kaguyaconversation.Table, kaguyaconversation.FieldID, selector),
			sqlgraph.To(kaguyachatturn.Table, kaguyachatturn.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, kaguyaconversation.TurnsTable, kaguyaconversation.TurnsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProject chains the current query on the "project" edge.
func (_q *KaguyaConversationQuery) QueryProject() *KaguyaProjectQuery {
	query := (&KaguyaProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(kaguyaconversation.Table, kaguyaconversation.FieldID, selector),
			sqlgraph.To(kaguyaproject.Table, kaguyaproject.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, kaguyaconversation.ProjectTable, kaguyaconversation.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first KaguyaConversation entity from the query.
// Returns a *NotFoundError when no KaguyaConversation was found.
func (_q *KaguyaConversationQuery) First(ctx context.Context) (*KaguyaConversation, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{kaguyaconversation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *KaguyaConversationQuery) FirstX(ctx context.Context) *KaguyaConversation {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first KaguyaConversation ID from the query.
// Returns a *NotFoundError when no KaguyaConversation ID was found.
func (_q *KaguyaConversationQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{kaguyaconversation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *KaguyaConversationQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single KaguyaConversation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one KaguyaConversation entity is found.
// Returns a *NotFoundError when no KaguyaConversation entities are found.
func (_q *KaguyaConversationQuery) Only(ctx context.Context) (*KaguyaConversation, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{kaguyaconversation.Label}
	default:
		return nil, &NotSingularError{kaguyaconversation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *KaguyaConversationQuery) OnlyX(ctx context.Context) *KaguyaConversation {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only KaguyaConversation ID in the query.
// Returns a *NotSingularError when more than one KaguyaConversation ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *KaguyaConversationQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{kaguyaconversation.Label}
	default:
		err = &NotSingularError{kaguyaconversation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *KaguyaConversationQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of KaguyaConversations.
func (_q *KaguyaConversationQuery) All(ctx context.Context) ([]*KaguyaConversation, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*KaguyaConversation, *KaguyaConversationQuery]()
	return withInterceptors[[]*KaguyaConversation](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *KaguyaConversationQuery) AllX(ctx context.Context) []*KaguyaConversation {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of KaguyaConversation IDs.
func (_q *KaguyaConversationQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(kaguyaconversation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *KaguyaConversationQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *KaguyaConversationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*KaguyaConversationQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *KaguyaConversationQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *KaguyaConversationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *KaguyaConversationQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the KaguyaConversationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *KaguyaConversationQuery) Clone() *KaguyaConversationQuery {
	if _q == nil {
		return nil
	}
	return &KaguyaConversationQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]kaguyaconversation.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.KaguyaConversation{}, _q.predicates...),
		withTurns:   _q.withTurns.Clone(),
		withProject: _q.withProject.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTurns tells the query-builder to eager-load the nodes that are connected to
// the "turns" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *KaguyaConversationQuery) WithTurns(opts ...func(*KaguyaChatTurnQuery)) *KaguyaConversationQuery {
	query := (&KaguyaChatTurnClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTurns = query
	return _q
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *KaguyaConversationQuery) WithProject(opts ...func(*KaguyaProjectQuery)) *KaguyaConversationQuery {
	query := (&KaguyaProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.KaguyaConversation.Query().
//		GroupBy(kaguyaconversation.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *KaguyaConversationQuery) GroupBy(field string, fields ...string) *KaguyaConversationGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &KaguyaConversationGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = kaguyaconversation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.KaguyaConversation.Query().
//		Select(kaguyaconversation.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *KaguyaConversationQuery) Select(fields ...string) *KaguyaConversationSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &KaguyaConversationSelect{KaguyaConversationQuery: _q}
	sbuild.label = kaguyaconversation.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a KaguyaConversationSelect configured with the given aggregations.
func (_q *KaguyaConversationQuery) Aggregate(fns ...AggregateFunc) *KaguyaConversationSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *KaguyaConversationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !kaguyaconversation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *KaguyaConversationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*KaguyaConversation, error) {
	var (
		nodes       = []*KaguyaConversation{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withTurns != nil,
			_q.withProject != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*KaguyaConversation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &KaguyaConversation{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTurns; query != nil {
		if err := _q.loadTurns(ctx, query, nodes,
			func(n *KaguyaConversation) { n.Edges.Turns = []*KaguyaChatTurn{} },
			func(n *KaguyaConversation, e *KaguyaChatTurn) { n.Edges.Turns = append(n.Edges.Turns, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *KaguyaConversation, e *KaguyaProject) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *KaguyaConversationQuery) loadTurns(ctx context.Context, query *KaguyaChatTurnQuery, nodes []*KaguyaConversation, init func(*KaguyaConversation), assign func(*KaguyaConversation, *KaguyaChatTurn)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*KaguyaConversation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(kaguyachatturn.FieldConversationID)
	}
	query.Where(predicate.KaguyaChatTurn(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(kaguyaconversation.TurnsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ConversationID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "conversation_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *KaguyaConversationQuery) loadProject(ctx context.Context, query *KaguyaProjectQuery, nodes []*KaguyaConversation, init func(*KaguyaConversation), assign func(*KaguyaConversation, *KaguyaProject)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*KaguyaConversation)
	for i := range nodes {
		if nodes[i].ProjectID == nil {
			continue
		}
		fk := *nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(kaguyaproject.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *KaguyaConversationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *KaguyaConversationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(kaguyaconversation.Table, kaguyaconversation.Columns, sqlgraph.NewFieldSpec(kaguyaconversation.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kaguyaconversation.FieldID)
		for i := range fields {
			if fields[i] != kaguyaconversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(kaguyaconversation.FieldProjectID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *KaguyaConversationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(kaguyaconversation.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = kaguyaconversation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *KaguyaConversationQuery) Modify(modifiers ...func(s *sql.Selector)) *KaguyaConversationSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// KaguyaConversationGroupBy is the group-by builder for KaguyaConversation entities.
type KaguyaConversationGroupBy struct {
	selector
	build *KaguyaConversationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *KaguyaConversationGroupBy) Aggregate(fns ...AggregateFunc) *KaguyaConversationGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *KaguyaConversationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*KaguyaConversationQuery, *KaguyaConversationGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *KaguyaConversationGroupBy) sqlScan(ctx context.Context, root *KaguyaConversationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// KaguyaConversationSelect is the builder for selecting fields of KaguyaConversation entities.
type KaguyaConversationSelect struct {
	*KaguyaConversationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *KaguyaConversationSelect) Aggregate(fns ...AggregateFunc) *KaguyaConversationSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *KaguyaConversationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*KaguyaConversationQuery, *KaguyaConversationSelect](ctx, _s.KaguyaConversationQuery, _s, _s.inters, v)
}

func (_s *KaguyaConversationSelect) sqlScan(ctx context.Context, root *KaguyaConversationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *KaguyaConversationSelect) Modify(modifiers ...func(s *sql.Selector)) *KaguyaConversationSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
