// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/kaguya/internal/ent/kaguyaaccesslog"
)

// KaguyaAccessLogCreate is the builder for creating a KaguyaAccessLog entity.
type KaguyaAccessLogCreate struct {
	config
	mutation *KaguyaAccessLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *KaguyaAccessLogCreate) SetCreatedAt(v time.Time) *KaguyaAccessLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableCreatedAt(v *time.Time) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *KaguyaAccessLogCreate) SetUpdatedAt(v time.Time) *KaguyaAccessLogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableUpdatedAt(v *time.Time) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *KaguyaAccessLogCreate) SetDeletedAt(v time.Time) *KaguyaAccessLogCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableDeletedAt(v *time.Time) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetAccessIP sets the "access_ip" field.
func (_c *KaguyaAccessLogCreate) SetAccessIP(v string) *KaguyaAccessLogCreate {
	_c.mutation.SetAccessIP(v)
	return _c
}

// SetNillableAccessIP sets the "access_ip" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableAccessIP(v *string) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetAccessIP(*v)
	}
	return _c
}

// SetAccessTime sets the "access_time" field.
func (_c *KaguyaAccessLogCreate) SetAccessTime(v int64) *KaguyaAccessLogCreate {
	_c.mutation.SetAccessTime(v)
	return _c
}

// SetNillableAccessTime sets the "access_time" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableAccessTime(v *int64) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetAccessTime(*v)
	}
	return _c
}

// SetOs sets the "os" field.
func (_c *KaguyaAccessLogCreate) SetOs(v string) *KaguyaAccessLogCreate {
	_c.mutation.SetOs(v)
	return _c
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableOs(v *string) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetOs(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *KaguyaAccessLogCreate) SetPlatform(v string) *KaguyaAccessLogCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillablePlatform(v *string) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetBrowserName sets the "browser_name" field.
func (_c *KaguyaAccessLogCreate) SetBrowserName(v string) *KaguyaAccessLogCreate {
	_c.mutation.SetBrowserName(v)
	return _c
}

// SetNillableBrowserName sets the "browser_name" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableBrowserName(v *string) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetBrowserName(*v)
	}
	return _c
}

// SetBrowserVersion sets the "browser_version" field.
func (_c *KaguyaAccessLogCreate) SetBrowserVersion(v string) *KaguyaAccessLogCreate {
	_c.mutation.SetBrowserVersion(v)
	return _c
}

// SetNillableBrowserVersion sets the "browser_version" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableBrowserVersion(v *string) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetBrowserVersion(*v)
	}
	return _c
}

// SetBrowserEngineName sets the "browser_engine_name" field.
func (_c *KaguyaAccessLogCreate) SetBrowserEngineName(v string) *KaguyaAccessLogCreate {
	_c.mutation.SetBrowserEngineName(v)
	return _c
}

// SetNillableBrowserEngineName sets the "browser_engine_name" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableBrowserEngineName(v *string) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetBrowserEngineName(*v)
	}
	return _c
}

// SetBrowserEngineVersion sets the "browser_engine_version" field.
func (_c *KaguyaAccessLogCreate) SetBrowserEngineVersion(v string) *KaguyaAccessLogCreate {
	_c.mutation.SetBrowserEngineVersion(v)
	return _c
}

// SetNillableBrowserEngineVersion sets the "browser_engine_version" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableBrowserEngineVersion(v *string) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetBrowserEngineVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *KaguyaAccessLogCreate) SetID(v string) *KaguyaAccessLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KaguyaAccessLogCreate) SetNillableID(v *string) *KaguyaAccessLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the KaguyaAccessLogMutation object of the builder.
func (_c *KaguyaAccessLogCreate) Mutation() *KaguyaAccessLogMutation {
	return _c.mutation
}

// Save creates the KaguyaAccessLog in the database.
func (_c *KaguyaAccessLogCreate) Save(ctx context.Context) (*KaguyaAccessLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KaguyaAccessLogCreate) SaveX(ctx context.Context) *KaguyaAccessLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KaguyaAccessLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KaguyaAccessLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KaguyaAccessLogCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if kaguyaaccesslog.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyaaccesslog.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyaaccesslog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if kaguyaaccesslog.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyaaccesslog.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyaaccesslog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AccessTime(); !ok {
		if kaguyaaccesslog.DefaultAccessTime == nil {
			return fmt.Errorf("ent: uninitialized kaguyaaccesslog.DefaultAccessTime (forgotten import ent/runtime?)")
		}
		v := kaguyaaccesslog.DefaultAccessTime()
		_c.mutation.SetAccessTime(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if kaguyaaccesslog.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized kaguyaaccesslog.DefaultID (forgotten import ent/runtime?)")
		}
		v := kaguyaaccesslog.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *KaguyaAccessLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KaguyaAccessLog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "KaguyaAccessLog.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := kaguyaaccesslog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "KaguyaAccessLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *KaguyaAccessLogCreate) sqlSave(ctx context.Context) (*KaguyaAccessLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected KaguyaAccessLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KaguyaAccessLogCreate) createSpec() (*KaguyaAccessLog, *sqlgraph.CreateSpec) {
	var (
		_node = &KaguyaAccessLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(kaguyaaccesslog.Table, sqlgraph.NewFieldSpec(kaguyaaccesslog.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(kaguyaaccesslog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyaaccesslog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyaaccesslog.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.AccessIP(); ok {
		_spec.SetField(kaguyaaccesslog.FieldAccessIP, field.TypeString, value)
		_node.AccessIP = value
	}
	if value, ok := _c.mutation.AccessTime(); ok {
		_spec.SetField(kaguyaaccesslog.FieldAccessTime, field.TypeInt64, value)
		_node.AccessTime = value
	}
	if value, ok := _c.mutation.Os(); ok {
		_spec.SetField(kaguyaaccesslog.FieldOs, field.TypeString, value)
		_node.Os = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(kaguyaaccesslog.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.BrowserName(); ok {
		_spec.SetField(kaguyaaccesslog.FieldBrowserName, field.TypeString, value)
		_node.BrowserName = value
	}
	if value, ok := _c.mutation.BrowserVersion(); ok {
		_spec.SetField(kaguyaaccesslog.FieldBrowserVersion, field.TypeString, value)
		_node.BrowserVersion = value
	}
	if value, ok := _c.mutation.BrowserEngineName(); ok {
		_spec.SetField(kaguyaaccesslog.FieldBrowserEngineName, field.TypeString, value)
		_node.BrowserEngineName = value
	}
	if value, ok := _c.mutation.BrowserEngineVersion(); ok {
		_spec.SetField(kaguyaaccesslog.FieldBrowserEngineVersion, field.TypeString, value)
		_node.BrowserEngineVersion = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KaguyaAccessLog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KaguyaAccessLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *KaguyaAccessLogCreate) OnConflict(opts ...sql.ConflictOption) *KaguyaAccessLogUpsertOne {
	_c.conflict = opts
	return &KaguyaAccessLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KaguyaAccessLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KaguyaAccessLogCreate) OnConflictColumns(columns ...string) *KaguyaAccessLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KaguyaAccessLogUpsertOne{
		create: _c,
	}
}

type (
	// KaguyaAccessLogUpsertOne is the builder for "upsert"-ing
	//  one KaguyaAccessLog node.
	KaguyaAccessLogUpsertOne struct {
		create *KaguyaAccessLogCreate
	}

	// KaguyaAccessLogUpsert is the "OnConflict" setter.
	KaguyaAccessLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *KaguyaAccessLogUpsert) SetUpdatedAt(v time.Time) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateUpdatedAt() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *KaguyaAccessLogUpsert) SetDeletedAt(v time.Time) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateDeletedAt() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *KaguyaAccessLogUpsert) ClearDeletedAt() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldDeletedAt)
	return u
}

// SetAccessIP sets the "access_ip" field.
func (u *KaguyaAccessLogUpsert) SetAccessIP(v string) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldAccessIP, v)
	return u
}

// UpdateAccessIP sets the "access_ip" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateAccessIP() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldAccessIP)
	return u
}

// ClearAccessIP clears the value of the "access_ip" field.
func (u *KaguyaAccessLogUpsert) ClearAccessIP() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldAccessIP)
	return u
}

// SetAccessTime sets the "access_time" field.
func (u *KaguyaAccessLogUpsert) SetAccessTime(v int64) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldAccessTime, v)
	return u
}

// UpdateAccessTime sets the "access_time" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateAccessTime() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldAccessTime)
	return u
}

// AddAccessTime adds v to the "access_time" field.
func (u *KaguyaAccessLogUpsert) AddAccessTime(v int64) *KaguyaAccessLogUpsert {
	u.Add(kaguyaaccesslog.FieldAccessTime, v)
	return u
}

// ClearAccessTime clears the value of the "access_time" field.
func (u *KaguyaAccessLogUpsert) ClearAccessTime() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldAccessTime)
	return u
}

// SetOs sets the "os" field.
func (u *KaguyaAccessLogUpsert) SetOs(v string) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldOs, v)
	return u
}

// UpdateOs sets the "os" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateOs() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldOs)
	return u
}

// ClearOs clears the value of the "os" field.
func (u *KaguyaAccessLogUpsert) ClearOs() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldOs)
	return u
}

// SetPlatform sets the "platform" field.
func (u *KaguyaAccessLogUpsert) SetPlatform(v string) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdatePlatform() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldPlatform)
	return u
}

// ClearPlatform clears the value of the "platform" field.
func (u *KaguyaAccessLogUpsert) ClearPlatform() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldPlatform)
	return u
}

// SetBrowserName sets the "browser_name" field.
func (u *KaguyaAccessLogUpsert) SetBrowserName(v string) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldBrowserName, v)
	return u
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateBrowserName() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldBrowserName)
	return u
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *KaguyaAccessLogUpsert) ClearBrowserName() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldBrowserName)
	return u
}

// SetBrowserVersion sets the "browser_version" field.
func (u *KaguyaAccessLogUpsert) SetBrowserVersion(v string) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldBrowserVersion, v)
	return u
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateBrowserVersion() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldBrowserVersion)
	return u
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *KaguyaAccessLogUpsert) ClearBrowserVersion() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldBrowserVersion)
	return u
}

// SetBrowserEngineName sets the "browser_engine_name" field.
func (u *KaguyaAccessLogUpsert) SetBrowserEngineName(v string) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldBrowserEngineName, v)
	return u
}

// UpdateBrowserEngineName sets the "browser_engine_name" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateBrowserEngineName() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldBrowserEngineName)
	return u
}

// ClearBrowserEngineName clears the value of the "browser_engine_name" field.
func (u *KaguyaAccessLogUpsert) ClearBrowserEngineName() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldBrowserEngineName)
	return u
}

// SetBrowserEngineVersion sets the "browser_engine_version" field.
func (u *KaguyaAccessLogUpsert) SetBrowserEngineVersion(v string) *KaguyaAccessLogUpsert {
	u.Set(kaguyaaccesslog.FieldBrowserEngineVersion, v)
	return u
}

// UpdateBrowserEngineVersion sets the "browser_engine_version" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsert) UpdateBrowserEngineVersion() *KaguyaAccessLogUpsert {
	u.SetExcluded(kaguyaaccesslog.FieldBrowserEngineVersion)
	return u
}

// ClearBrowserEngineVersion clears the value of the "browser_engine_version" field.
func (u *KaguyaAccessLogUpsert) ClearBrowserEngineVersion() *KaguyaAccessLogUpsert {
	u.SetNull(kaguyaaccesslog.FieldBrowserEngineVersion)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.KaguyaAccessLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(kaguyaaccesslog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KaguyaAccessLogUpsertOne) UpdateNewValues() *KaguyaAccessLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(kaguyaaccesslog.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(kaguyaaccesslog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KaguyaAccessLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *KaguyaAccessLogUpsertOne) Ignore() *KaguyaAccessLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KaguyaAccessLogUpsertOne) DoNothing() *KaguyaAccessLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KaguyaAccessLogCreate.OnConflict
// documentation for more info.
func (u *KaguyaAccessLogUpsertOne) Update(set func(*KaguyaAccessLogUpsert)) *KaguyaAccessLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KaguyaAccessLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KaguyaAccessLogUpsertOne) SetUpdatedAt(v time.Time) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateUpdatedAt() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *KaguyaAccessLogUpsertOne) SetDeletedAt(v time.Time) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateDeletedAt() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *KaguyaAccessLogUpsertOne) ClearDeletedAt() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearDeletedAt()
	})
}

// SetAccessIP sets the "access_ip" field.
func (u *KaguyaAccessLogUpsertOne) SetAccessIP(v string) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetAccessIP(v)
	})
}

// UpdateAccessIP sets the "access_ip" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateAccessIP() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateAccessIP()
	})
}

// ClearAccessIP clears the value of the "access_ip" field.
func (u *KaguyaAccessLogUpsertOne) ClearAccessIP() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearAccessIP()
	})
}

// SetAccessTime sets the "access_time" field.
func (u *KaguyaAccessLogUpsertOne) SetAccessTime(v int64) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetAccessTime(v)
	})
}

// AddAccessTime adds v to the "access_time" field.
func (u *KaguyaAccessLogUpsertOne) AddAccessTime(v int64) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.AddAccessTime(v)
	})
}

// UpdateAccessTime sets the "access_time" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateAccessTime() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateAccessTime()
	})
}

// ClearAccessTime clears the value of the "access_time" field.
func (u *KaguyaAccessLogUpsertOne) ClearAccessTime() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearAccessTime()
	})
}

// SetOs sets the "os" field.
func (u *KaguyaAccessLogUpsertOne) SetOs(v string) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetOs(v)
	})
}

// UpdateOs sets the "os" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateOs() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateOs()
	})
}

// ClearOs clears the value of the "os" field.
func (u *KaguyaAccessLogUpsertOne) ClearOs() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearOs()
	})
}

// SetPlatform sets the "platform" field.
func (u *KaguyaAccessLogUpsertOne) SetPlatform(v string) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdatePlatform() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *KaguyaAccessLogUpsertOne) ClearPlatform() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearPlatform()
	})
}

// SetBrowserName sets the "browser_name" field.
func (u *KaguyaAccessLogUpsertOne) SetBrowserName(v string) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetBrowserName(v)
	})
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateBrowserName() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateBrowserName()
	})
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *KaguyaAccessLogUpsertOne) ClearBrowserName() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearBrowserName()
	})
}

// SetBrowserVersion sets the "browser_version" field.
func (u *KaguyaAccessLogUpsertOne) SetBrowserVersion(v string) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetBrowserVersion(v)
	})
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateBrowserVersion() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateBrowserVersion()
	})
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *KaguyaAccessLogUpsertOne) ClearBrowserVersion() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearBrowserVersion()
	})
}

// SetBrowserEngineName sets the "browser_engine_name" field.
func (u *KaguyaAccessLogUpsertOne) SetBrowserEngineName(v string) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetBrowserEngineName(v)
	})
}

// UpdateBrowserEngineName sets the "browser_engine_name" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateBrowserEngineName() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateBrowserEngineName()
	})
}

// ClearBrowserEngineName clears the value of the "browser_engine_name" field.
func (u *KaguyaAccessLogUpsertOne) ClearBrowserEngineName() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearBrowserEngineName()
	})
}

// SetBrowserEngineVersion sets the "browser_engine_version" field.
func (u *KaguyaAccessLogUpsertOne) SetBrowserEngineVersion(v string) *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetBrowserEngineVersion(v)
	})
}

// UpdateBrowserEngineVersion sets the "browser_engine_version" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertOne) UpdateBrowserEngineVersion() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateBrowserEngineVersion()
	})
}

// ClearBrowserEngineVersion clears the value of the "browser_engine_version" field.
func (u *KaguyaAccessLogUpsertOne) ClearBrowserEngineVersion() *KaguyaAccessLogUpsertOne {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearBrowserEngineVersion()
	})
}

// Exec executes the query.
func (u *KaguyaAccessLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KaguyaAccessLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KaguyaAccessLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *KaguyaAccessLogUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: KaguyaAccessLogUpsertOne.ID is not supported by MySQL driver. Use KaguyaAccessLogUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *KaguyaAccessLogUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// KaguyaAccessLogCreateBulk is the builder for creating many KaguyaAccessLog entities in bulk.
type KaguyaAccessLogCreateBulk struct {
	config
	err      error
	builders []*KaguyaAccessLogCreate
	conflict []sql.ConflictOption
}

// Save creates the KaguyaAccessLog entities in the database.
func (_c *KaguyaAccessLogCreateBulk) Save(ctx context.Context) ([]*KaguyaAccessLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KaguyaAccessLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KaguyaAccessLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KaguyaAccessLogCreateBulk) SaveX(ctx context.Context) []*KaguyaAccessLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KaguyaAccessLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KaguyaAccessLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KaguyaAccessLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KaguyaAccessLogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *KaguyaAccessLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *KaguyaAccessLogUpsertBulk {
	_c.conflict = opts
	return &KaguyaAccessLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KaguyaAccessLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KaguyaAccessLogCreateBulk) OnConflictColumns(columns ...string) *KaguyaAccessLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KaguyaAccessLogUpsertBulk{
		create: _c,
	}
}

// KaguyaAccessLogUpsertBulk is the builder for "upsert"-ing
// a bulk of KaguyaAccessLog nodes.
type KaguyaAccessLogUpsertBulk struct {
	create *KaguyaAccessLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.KaguyaAccessLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(kaguyaaccesslog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KaguyaAccessLogUpsertBulk) UpdateNewValues() *KaguyaAccessLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(kaguyaaccesslog.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(kaguyaaccesslog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KaguyaAccessLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *KaguyaAccessLogUpsertBulk) Ignore() *KaguyaAccessLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KaguyaAccessLogUpsertBulk) DoNothing() *KaguyaAccessLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KaguyaAccessLogCreateBulk.OnConflict
// documentation for more info.
func (u *KaguyaAccessLogUpsertBulk) Update(set func(*KaguyaAccessLogUpsert)) *KaguyaAccessLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KaguyaAccessLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KaguyaAccessLogUpsertBulk) SetUpdatedAt(v time.Time) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateUpdatedAt() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *KaguyaAccessLogUpsertBulk) SetDeletedAt(v time.Time) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateDeletedAt() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *KaguyaAccessLogUpsertBulk) ClearDeletedAt() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearDeletedAt()
	})
}

// SetAccessIP sets the "access_ip" field.
func (u *KaguyaAccessLogUpsertBulk) SetAccessIP(v string) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetAccessIP(v)
	})
}

// UpdateAccessIP sets the "access_ip" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateAccessIP() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateAccessIP()
	})
}

// ClearAccessIP clears the value of the "access_ip" field.
func (u *KaguyaAccessLogUpsertBulk) ClearAccessIP() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearAccessIP()
	})
}

// SetAccessTime sets the "access_time" field.
func (u *KaguyaAccessLogUpsertBulk) SetAccessTime(v int64) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetAccessTime(v)
	})
}

// AddAccessTime adds v to the "access_time" field.
func (u *KaguyaAccessLogUpsertBulk) AddAccessTime(v int64) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.AddAccessTime(v)
	})
}

// UpdateAccessTime sets the "access_time" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateAccessTime() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateAccessTime()
	})
}

// ClearAccessTime clears the value of the "access_time" field.
func (u *KaguyaAccessLogUpsertBulk) ClearAccessTime() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearAccessTime()
	})
}

// SetOs sets the "os" field.
func (u *KaguyaAccessLogUpsertBulk) SetOs(v string) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetOs(v)
	})
}

// UpdateOs sets the "os" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateOs() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateOs()
	})
}

// ClearOs clears the value of the "os" field.
func (u *KaguyaAccessLogUpsertBulk) ClearOs() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearOs()
	})
}

// SetPlatform sets the "platform" field.
func (u *KaguyaAccessLogUpsertBulk) SetPlatform(v string) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdatePlatform() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdatePlatform()
	})
}

// ClearPlatform clears the value of the "platform" field.
func (u *KaguyaAccessLogUpsertBulk) ClearPlatform() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearPlatform()
	})
}

// SetBrowserName sets the "browser_name" field.
func (u *KaguyaAccessLogUpsertBulk) SetBrowserName(v string) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetBrowserName(v)
	})
}

// UpdateBrowserName sets the "browser_name" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateBrowserName() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateBrowserName()
	})
}

// ClearBrowserName clears the value of the "browser_name" field.
func (u *KaguyaAccessLogUpsertBulk) ClearBrowserName() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearBrowserName()
	})
}

// SetBrowserVersion sets the "browser_version" field.
func (u *KaguyaAccessLogUpsertBulk) SetBrowserVersion(v string) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetBrowserVersion(v)
	})
}

// UpdateBrowserVersion sets the "browser_version" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateBrowserVersion() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateBrowserVersion()
	})
}

// ClearBrowserVersion clears the value of the "browser_version" field.
func (u *KaguyaAccessLogUpsertBulk) ClearBrowserVersion() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearBrowserVersion()
	})
}

// SetBrowserEngineName sets the "browser_engine_name" field.
func (u *KaguyaAccessLogUpsertBulk) SetBrowserEngineName(v string) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetBrowserEngineName(v)
	})
}

// UpdateBrowserEngineName sets the "browser_engine_name" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateBrowserEngineName() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateBrowserEngineName()
	})
}

// ClearBrowserEngineName clears the value of the "browser_engine_name" field.
func (u *KaguyaAccessLogUpsertBulk) ClearBrowserEngineName() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearBrowserEngineName()
	})
}

// SetBrowserEngineVersion sets the "browser_engine_version" field.
func (u *KaguyaAccessLogUpsertBulk) SetBrowserEngineVersion(v string) *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.SetBrowserEngineVersion(v)
	})
}

// UpdateBrowserEngineVersion sets the "browser_engine_version" field to the value that was provided on create.
func (u *KaguyaAccessLogUpsertBulk) UpdateBrowserEngineVersion() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.UpdateBrowserEngineVersion()
	})
}

// ClearBrowserEngineVersion clears the value of the "browser_engine_version" field.
func (u *KaguyaAccessLogUpsertBulk) ClearBrowserEngineVersion() *KaguyaAccessLogUpsertBulk {
	return u.Update(func(s *KaguyaAccessLogUpsert) {
		s.ClearBrowserEngineVersion()
	})
}

// Exec executes the query.
func (u *KaguyaAccessLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the KaguyaAccessLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KaguyaAccessLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KaguyaAccessLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
