// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lyonmu/kaguya/internal/consts"
	"github.com/lyonmu/kaguya/internal/ent/kaguyamodelsinfo"
	"github.com/lyonmu/kaguya/internal/ent/kaguyaproviderinfo"
	"github.com/lyonmu/kaguya/internal/ent/predicate"
)

// KaguyaModelsInfoUpdate is the builder for updating KaguyaModelsInfo entities.
type KaguyaModelsInfoUpdate struct {
	config
	hooks     []Hook
	mutation  *KaguyaModelsInfoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the KaguyaModelsInfoUpdate builder.
func (_u *KaguyaModelsInfoUpdate) Where(ps ...predicate.KaguyaModelsInfo) *KaguyaModelsInfoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KaguyaModelsInfoUpdate) SetUpdatedAt(v time.Time) *KaguyaModelsInfoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KaguyaModelsInfoUpdate) SetDeletedAt(v time.Time) *KaguyaModelsInfoUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableDeletedAt(v *time.Time) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KaguyaModelsInfoUpdate) ClearDeletedAt() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *KaguyaModelsInfoUpdate) SetProviderID(v string) *KaguyaModelsInfoUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableProviderID(v *string) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *KaguyaModelsInfoUpdate) SetModelName(v string) *KaguyaModelsInfoUpdate {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableModelName(v *string) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *KaguyaModelsInfoUpdate) SetModelID(v string) *KaguyaModelsInfoUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableModelID(v *string) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetReasoningEnabled sets the "reasoning_enabled" field.
func (_u *KaguyaModelsInfoUpdate) SetReasoningEnabled(v consts.Status) *KaguyaModelsInfoUpdate {
	_u.mutation.ResetReasoningEnabled()
	_u.mutation.SetReasoningEnabled(v)
	return _u
}

// SetNillableReasoningEnabled sets the "reasoning_enabled" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableReasoningEnabled(v *consts.Status) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetReasoningEnabled(*v)
	}
	return _u
}

// AddReasoningEnabled adds value to the "reasoning_enabled" field.
func (_u *KaguyaModelsInfoUpdate) AddReasoningEnabled(v consts.Status) *KaguyaModelsInfoUpdate {
	_u.mutation.AddReasoningEnabled(v)
	return _u
}

// ClearReasoningEnabled clears the value of the "reasoning_enabled" field.
func (_u *KaguyaModelsInfoUpdate) ClearReasoningEnabled() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearReasoningEnabled()
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *KaguyaModelsInfoUpdate) SetReasoningEffort(v consts.ReasoningEffort) *KaguyaModelsInfoUpdate {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableReasoningEffort(v *consts.ReasoningEffort) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// ClearReasoningEffort clears the value of the "reasoning_effort" field.
func (_u *KaguyaModelsInfoUpdate) ClearReasoningEffort() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearReasoningEffort()
	return _u
}

// SetTokenContextWindow sets the "token_context_window" field.
func (_u *KaguyaModelsInfoUpdate) SetTokenContextWindow(v int) *KaguyaModelsInfoUpdate {
	_u.mutation.ResetTokenContextWindow()
	_u.mutation.SetTokenContextWindow(v)
	return _u
}

// SetNillableTokenContextWindow sets the "token_context_window" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableTokenContextWindow(v *int) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetTokenContextWindow(*v)
	}
	return _u
}

// AddTokenContextWindow adds value to the "token_context_window" field.
func (_u *KaguyaModelsInfoUpdate) AddTokenContextWindow(v int) *KaguyaModelsInfoUpdate {
	_u.mutation.AddTokenContextWindow(v)
	return _u
}

// ClearTokenContextWindow clears the value of the "token_context_window" field.
func (_u *KaguyaModelsInfoUpdate) ClearTokenContextWindow() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearTokenContextWindow()
	return _u
}

// SetTokenMaxOutputTokens sets the "token_max_output_tokens" field.
func (_u *KaguyaModelsInfoUpdate) SetTokenMaxOutputTokens(v int) *KaguyaModelsInfoUpdate {
	_u.mutation.ResetTokenMaxOutputTokens()
	_u.mutation.SetTokenMaxOutputTokens(v)
	return _u
}

// SetNillableTokenMaxOutputTokens sets the "token_max_output_tokens" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableTokenMaxOutputTokens(v *int) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetTokenMaxOutputTokens(*v)
	}
	return _u
}

// AddTokenMaxOutputTokens adds value to the "token_max_output_tokens" field.
func (_u *KaguyaModelsInfoUpdate) AddTokenMaxOutputTokens(v int) *KaguyaModelsInfoUpdate {
	_u.mutation.AddTokenMaxOutputTokens(v)
	return _u
}

// ClearTokenMaxOutputTokens clears the value of the "token_max_output_tokens" field.
func (_u *KaguyaModelsInfoUpdate) ClearTokenMaxOutputTokens() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearTokenMaxOutputTokens()
	return _u
}

// SetCapabilityToolUse sets the "capability_tool_use" field.
func (_u *KaguyaModelsInfoUpdate) SetCapabilityToolUse(v consts.Status) *KaguyaModelsInfoUpdate {
	_u.mutation.ResetCapabilityToolUse()
	_u.mutation.SetCapabilityToolUse(v)
	return _u
}

// SetNillableCapabilityToolUse sets the "capability_tool_use" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableCapabilityToolUse(v *consts.Status) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetCapabilityToolUse(*v)
	}
	return _u
}

// AddCapabilityToolUse adds value to the "capability_tool_use" field.
func (_u *KaguyaModelsInfoUpdate) AddCapabilityToolUse(v consts.Status) *KaguyaModelsInfoUpdate {
	_u.mutation.AddCapabilityToolUse(v)
	return _u
}

// ClearCapabilityToolUse clears the value of the "capability_tool_use" field.
func (_u *KaguyaModelsInfoUpdate) ClearCapabilityToolUse() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearCapabilityToolUse()
	return _u
}

// SetCapabilityVision sets the "capability_vision" field.
func (_u *KaguyaModelsInfoUpdate) SetCapabilityVision(v consts.Status) *KaguyaModelsInfoUpdate {
	_u.mutation.ResetCapabilityVision()
	_u.mutation.SetCapabilityVision(v)
	return _u
}

// SetNillableCapabilityVision sets the "capability_vision" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableCapabilityVision(v *consts.Status) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetCapabilityVision(*v)
	}
	return _u
}

// AddCapabilityVision adds value to the "capability_vision" field.
func (_u *KaguyaModelsInfoUpdate) AddCapabilityVision(v consts.Status) *KaguyaModelsInfoUpdate {
	_u.mutation.AddCapabilityVision(v)
	return _u
}

// ClearCapabilityVision clears the value of the "capability_vision" field.
func (_u *KaguyaModelsInfoUpdate) ClearCapabilityVision() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearCapabilityVision()
	return _u
}

// SetCapabilityStructuredOutput sets the "capability_structured_output" field.
func (_u *KaguyaModelsInfoUpdate) SetCapabilityStructuredOutput(v consts.Status) *KaguyaModelsInfoUpdate {
	_u.mutation.ResetCapabilityStructuredOutput()
	_u.mutation.SetCapabilityStructuredOutput(v)
	return _u
}

// SetNillableCapabilityStructuredOutput sets the "capability_structured_output" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdate) SetNillableCapabilityStructuredOutput(v *consts.Status) *KaguyaModelsInfoUpdate {
	if v != nil {
		_u.SetCapabilityStructuredOutput(*v)
	}
	return _u
}

// AddCapabilityStructuredOutput adds value to the "capability_structured_output" field.
func (_u *KaguyaModelsInfoUpdate) AddCapabilityStructuredOutput(v consts.Status) *KaguyaModelsInfoUpdate {
	_u.mutation.AddCapabilityStructuredOutput(v)
	return _u
}

// ClearCapabilityStructuredOutput clears the value of the "capability_structured_output" field.
func (_u *KaguyaModelsInfoUpdate) ClearCapabilityStructuredOutput() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearCapabilityStructuredOutput()
	return _u
}

// SetProvider sets the "provider" edge to the KaguyaProviderInfo entity.
func (_u *KaguyaModelsInfoUpdate) SetProvider(v *KaguyaProviderInfo) *KaguyaModelsInfoUpdate {
	return _u.SetProviderID(v.ID)
}

// Mutation returns the KaguyaModelsInfoMutation object of the builder.
func (_u *KaguyaModelsInfoUpdate) Mutation() *KaguyaModelsInfoMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the KaguyaProviderInfo entity.
func (_u *KaguyaModelsInfoUpdate) ClearProvider() *KaguyaModelsInfoUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KaguyaModelsInfoUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KaguyaModelsInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KaguyaModelsInfoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KaguyaModelsInfoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KaguyaModelsInfoUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if kaguyamodelsinfo.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyamodelsinfo.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyamodelsinfo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KaguyaModelsInfoUpdate) check() error {
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := kaguyamodelsinfo.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "KaguyaModelsInfo.provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := kaguyamodelsinfo.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "KaguyaModelsInfo.model_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelID(); ok {
		if err := kaguyamodelsinfo.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "KaguyaModelsInfo.model_id": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KaguyaModelsInfo.provider"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KaguyaModelsInfoUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KaguyaModelsInfoUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KaguyaModelsInfoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kaguyamodelsinfo.Table, kaguyamodelsinfo.Columns, sqlgraph.NewFieldSpec(kaguyamodelsinfo.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEnabled(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldReasoningEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReasoningEnabled(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldReasoningEnabled, field.TypeInt, value)
	}
	if _u.mutation.ReasoningEnabledCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldReasoningEnabled, field.TypeInt)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldReasoningEffort, field.TypeString, value)
	}
	if _u.mutation.ReasoningEffortCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldReasoningEffort, field.TypeString)
	}
	if value, ok := _u.mutation.TokenContextWindow(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldTokenContextWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenContextWindow(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldTokenContextWindow, field.TypeInt, value)
	}
	if _u.mutation.TokenContextWindowCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldTokenContextWindow, field.TypeInt)
	}
	if value, ok := _u.mutation.TokenMaxOutputTokens(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldTokenMaxOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenMaxOutputTokens(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldTokenMaxOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.TokenMaxOutputTokensCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldTokenMaxOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.CapabilityToolUse(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldCapabilityToolUse, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapabilityToolUse(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldCapabilityToolUse, field.TypeInt, value)
	}
	if _u.mutation.CapabilityToolUseCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldCapabilityToolUse, field.TypeInt)
	}
	if value, ok := _u.mutation.CapabilityVision(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldCapabilityVision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapabilityVision(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldCapabilityVision, field.TypeInt, value)
	}
	if _u.mutation.CapabilityVisionCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldCapabilityVision, field.TypeInt)
	}
	if value, ok := _u.mutation.CapabilityStructuredOutput(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldCapabilityStructuredOutput, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapabilityStructuredOutput(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldCapabilityStructuredOutput, field.TypeInt, value)
	}
	if _u.mutation.CapabilityStructuredOutputCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldCapabilityStructuredOutput, field.TypeInt)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   kaguyamodelsinfo.ProviderTable,
			Columns: []string{kaguyamodelsinfo.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(kaguyaproviderinfo.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   kaguyamodelsinfo.ProviderTable,
			Columns: []string{kaguyamodelsinfo.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(kaguyaproviderinfo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kaguyamodelsinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KaguyaModelsInfoUpdateOne is the builder for updating a single KaguyaModelsInfo entity.
type KaguyaModelsInfoUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *KaguyaModelsInfoMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KaguyaModelsInfoUpdateOne) SetUpdatedAt(v time.Time) *KaguyaModelsInfoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KaguyaModelsInfoUpdateOne) SetDeletedAt(v time.Time) *KaguyaModelsInfoUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableDeletedAt(v *time.Time) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KaguyaModelsInfoUpdateOne) ClearDeletedAt() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *KaguyaModelsInfoUpdateOne) SetProviderID(v string) *KaguyaModelsInfoUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableProviderID(v *string) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetModelName sets the "model_name" field.
func (_u *KaguyaModelsInfoUpdateOne) SetModelName(v string) *KaguyaModelsInfoUpdateOne {
	_u.mutation.SetModelName(v)
	return _u
}

// SetNillableModelName sets the "model_name" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableModelName(v *string) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetModelName(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *KaguyaModelsInfoUpdateOne) SetModelID(v string) *KaguyaModelsInfoUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableModelID(v *string) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetReasoningEnabled sets the "reasoning_enabled" field.
func (_u *KaguyaModelsInfoUpdateOne) SetReasoningEnabled(v consts.Status) *KaguyaModelsInfoUpdateOne {
	_u.mutation.ResetReasoningEnabled()
	_u.mutation.SetReasoningEnabled(v)
	return _u
}

// SetNillableReasoningEnabled sets the "reasoning_enabled" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableReasoningEnabled(v *consts.Status) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetReasoningEnabled(*v)
	}
	return _u
}

// AddReasoningEnabled adds value to the "reasoning_enabled" field.
func (_u *KaguyaModelsInfoUpdateOne) AddReasoningEnabled(v consts.Status) *KaguyaModelsInfoUpdateOne {
	_u.mutation.AddReasoningEnabled(v)
	return _u
}

// ClearReasoningEnabled clears the value of the "reasoning_enabled" field.
func (_u *KaguyaModelsInfoUpdateOne) ClearReasoningEnabled() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearReasoningEnabled()
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *KaguyaModelsInfoUpdateOne) SetReasoningEffort(v consts.ReasoningEffort) *KaguyaModelsInfoUpdateOne {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableReasoningEffort(v *consts.ReasoningEffort) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// ClearReasoningEffort clears the value of the "reasoning_effort" field.
func (_u *KaguyaModelsInfoUpdateOne) ClearReasoningEffort() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearReasoningEffort()
	return _u
}

// SetTokenContextWindow sets the "token_context_window" field.
func (_u *KaguyaModelsInfoUpdateOne) SetTokenContextWindow(v int) *KaguyaModelsInfoUpdateOne {
	_u.mutation.ResetTokenContextWindow()
	_u.mutation.SetTokenContextWindow(v)
	return _u
}

// SetNillableTokenContextWindow sets the "token_context_window" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableTokenContextWindow(v *int) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetTokenContextWindow(*v)
	}
	return _u
}

// AddTokenContextWindow adds value to the "token_context_window" field.
func (_u *KaguyaModelsInfoUpdateOne) AddTokenContextWindow(v int) *KaguyaModelsInfoUpdateOne {
	_u.mutation.AddTokenContextWindow(v)
	return _u
}

// ClearTokenContextWindow clears the value of the "token_context_window" field.
func (_u *KaguyaModelsInfoUpdateOne) ClearTokenContextWindow() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearTokenContextWindow()
	return _u
}

// SetTokenMaxOutputTokens sets the "token_max_output_tokens" field.
func (_u *KaguyaModelsInfoUpdateOne) SetTokenMaxOutputTokens(v int) *KaguyaModelsInfoUpdateOne {
	_u.mutation.ResetTokenMaxOutputTokens()
	_u.mutation.SetTokenMaxOutputTokens(v)
	return _u
}

// SetNillableTokenMaxOutputTokens sets the "token_max_output_tokens" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableTokenMaxOutputTokens(v *int) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetTokenMaxOutputTokens(*v)
	}
	return _u
}

// AddTokenMaxOutputTokens adds value to the "token_max_output_tokens" field.
func (_u *KaguyaModelsInfoUpdateOne) AddTokenMaxOutputTokens(v int) *KaguyaModelsInfoUpdateOne {
	_u.mutation.AddTokenMaxOutputTokens(v)
	return _u
}

// ClearTokenMaxOutputTokens clears the value of the "token_max_output_tokens" field.
func (_u *KaguyaModelsInfoUpdateOne) ClearTokenMaxOutputTokens() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearTokenMaxOutputTokens()
	return _u
}

// SetCapabilityToolUse sets the "capability_tool_use" field.
func (_u *KaguyaModelsInfoUpdateOne) SetCapabilityToolUse(v consts.Status) *KaguyaModelsInfoUpdateOne {
	_u.mutation.ResetCapabilityToolUse()
	_u.mutation.SetCapabilityToolUse(v)
	return _u
}

// SetNillableCapabilityToolUse sets the "capability_tool_use" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableCapabilityToolUse(v *consts.Status) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetCapabilityToolUse(*v)
	}
	return _u
}

// AddCapabilityToolUse adds value to the "capability_tool_use" field.
func (_u *KaguyaModelsInfoUpdateOne) AddCapabilityToolUse(v consts.Status) *KaguyaModelsInfoUpdateOne {
	_u.mutation.AddCapabilityToolUse(v)
	return _u
}

// ClearCapabilityToolUse clears the value of the "capability_tool_use" field.
func (_u *KaguyaModelsInfoUpdateOne) ClearCapabilityToolUse() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearCapabilityToolUse()
	return _u
}

// SetCapabilityVision sets the "capability_vision" field.
func (_u *KaguyaModelsInfoUpdateOne) SetCapabilityVision(v consts.Status) *KaguyaModelsInfoUpdateOne {
	_u.mutation.ResetCapabilityVision()
	_u.mutation.SetCapabilityVision(v)
	return _u
}

// SetNillableCapabilityVision sets the "capability_vision" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableCapabilityVision(v *consts.Status) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetCapabilityVision(*v)
	}
	return _u
}

// AddCapabilityVision adds value to the "capability_vision" field.
func (_u *KaguyaModelsInfoUpdateOne) AddCapabilityVision(v consts.Status) *KaguyaModelsInfoUpdateOne {
	_u.mutation.AddCapabilityVision(v)
	return _u
}

// ClearCapabilityVision clears the value of the "capability_vision" field.
func (_u *KaguyaModelsInfoUpdateOne) ClearCapabilityVision() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearCapabilityVision()
	return _u
}

// SetCapabilityStructuredOutput sets the "capability_structured_output" field.
func (_u *KaguyaModelsInfoUpdateOne) SetCapabilityStructuredOutput(v consts.Status) *KaguyaModelsInfoUpdateOne {
	_u.mutation.ResetCapabilityStructuredOutput()
	_u.mutation.SetCapabilityStructuredOutput(v)
	return _u
}

// SetNillableCapabilityStructuredOutput sets the "capability_structured_output" field if the given value is not nil.
func (_u *KaguyaModelsInfoUpdateOne) SetNillableCapabilityStructuredOutput(v *consts.Status) *KaguyaModelsInfoUpdateOne {
	if v != nil {
		_u.SetCapabilityStructuredOutput(*v)
	}
	return _u
}

// AddCapabilityStructuredOutput adds value to the "capability_structured_output" field.
func (_u *KaguyaModelsInfoUpdateOne) AddCapabilityStructuredOutput(v consts.Status) *KaguyaModelsInfoUpdateOne {
	_u.mutation.AddCapabilityStructuredOutput(v)
	return _u
}

// ClearCapabilityStructuredOutput clears the value of the "capability_structured_output" field.
func (_u *KaguyaModelsInfoUpdateOne) ClearCapabilityStructuredOutput() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearCapabilityStructuredOutput()
	return _u
}

// SetProvider sets the "provider" edge to the KaguyaProviderInfo entity.
func (_u *KaguyaModelsInfoUpdateOne) SetProvider(v *KaguyaProviderInfo) *KaguyaModelsInfoUpdateOne {
	return _u.SetProviderID(v.ID)
}

// Mutation returns the KaguyaModelsInfoMutation object of the builder.
func (_u *KaguyaModelsInfoUpdateOne) Mutation() *KaguyaModelsInfoMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the KaguyaProviderInfo entity.
func (_u *KaguyaModelsInfoUpdateOne) ClearProvider() *KaguyaModelsInfoUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// Where appends a list predicates to the KaguyaModelsInfoUpdate builder.
func (_u *KaguyaModelsInfoUpdateOne) Where(ps ...predicate.KaguyaModelsInfo) *KaguyaModelsInfoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KaguyaModelsInfoUpdateOne) Select(field string, fields ...string) *KaguyaModelsInfoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KaguyaModelsInfo entity.
func (_u *KaguyaModelsInfoUpdateOne) Save(ctx context.Context) (*KaguyaModelsInfo, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KaguyaModelsInfoUpdateOne) SaveX(ctx context.Context) *KaguyaModelsInfo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KaguyaModelsInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KaguyaModelsInfoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KaguyaModelsInfoUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if kaguyamodelsinfo.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized kaguyamodelsinfo.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := kaguyamodelsinfo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KaguyaModelsInfoUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := kaguyamodelsinfo.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "KaguyaModelsInfo.provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelName(); ok {
		if err := kaguyamodelsinfo.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "KaguyaModelsInfo.model_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelID(); ok {
		if err := kaguyamodelsinfo.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "KaguyaModelsInfo.model_id": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KaguyaModelsInfo.provider"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *KaguyaModelsInfoUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *KaguyaModelsInfoUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *KaguyaModelsInfoUpdateOne) sqlSave(ctx context.Context) (_node *KaguyaModelsInfo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(kaguyamodelsinfo.Table, kaguyamodelsinfo.Columns, sqlgraph.NewFieldSpec(kaguyamodelsinfo.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KaguyaModelsInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, kaguyamodelsinfo.FieldID)
		for _, f := range fields {
			if !kaguyamodelsinfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != kaguyamodelsinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ModelName(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldModelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEnabled(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldReasoningEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReasoningEnabled(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldReasoningEnabled, field.TypeInt, value)
	}
	if _u.mutation.ReasoningEnabledCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldReasoningEnabled, field.TypeInt)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldReasoningEffort, field.TypeString, value)
	}
	if _u.mutation.ReasoningEffortCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldReasoningEffort, field.TypeString)
	}
	if value, ok := _u.mutation.TokenContextWindow(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldTokenContextWindow, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenContextWindow(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldTokenContextWindow, field.TypeInt, value)
	}
	if _u.mutation.TokenContextWindowCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldTokenContextWindow, field.TypeInt)
	}
	if value, ok := _u.mutation.TokenMaxOutputTokens(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldTokenMaxOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenMaxOutputTokens(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldTokenMaxOutputTokens, field.TypeInt, value)
	}
	if _u.mutation.TokenMaxOutputTokensCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldTokenMaxOutputTokens, field.TypeInt)
	}
	if value, ok := _u.mutation.CapabilityToolUse(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldCapabilityToolUse, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapabilityToolUse(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldCapabilityToolUse, field.TypeInt, value)
	}
	if _u.mutation.CapabilityToolUseCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldCapabilityToolUse, field.TypeInt)
	}
	if value, ok := _u.mutation.CapabilityVision(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldCapabilityVision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapabilityVision(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldCapabilityVision, field.TypeInt, value)
	}
	if _u.mutation.CapabilityVisionCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldCapabilityVision, field.TypeInt)
	}
	if value, ok := _u.mutation.CapabilityStructuredOutput(); ok {
		_spec.SetField(kaguyamodelsinfo.FieldCapabilityStructuredOutput, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapabilityStructuredOutput(); ok {
		_spec.AddField(kaguyamodelsinfo.FieldCapabilityStructuredOutput, field.TypeInt, value)
	}
	if _u.mutation.CapabilityStructuredOutputCleared() {
		_spec.ClearField(kaguyamodelsinfo.FieldCapabilityStructuredOutput, field.TypeInt)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   kaguyamodelsinfo.ProviderTable,
			Columns: []string{kaguyamodelsinfo.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(kaguyaproviderinfo.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   kaguyamodelsinfo.ProviderTable,
			Columns: []string{kaguyamodelsinfo.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(kaguyaproviderinfo.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &KaguyaModelsInfo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{kaguyamodelsinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
