// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// KaguyaModelsInfo is the predicate function for kaguyamodelsinfo builders.
type KaguyaModelsInfo func(*sql.Selector)

// KaguyaProviderInfo is the predicate function for kaguyaproviderinfo builders.
type KaguyaProviderInfo func(*sql.Selector)
