// Code generated by ent, DO NOT EDIT.

package kaguyamodelsinfo

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lyonmu/kaguya/internal/consts"
)

const (
	// Label holds the string label denoting the kaguyamodelsinfo type in the database.
	Label = "kaguya_models_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// FieldIsTask holds the string denoting the is_task field in the database.
	FieldIsTask = "is_task"
	// FieldReasoningEnabled holds the string denoting the reasoning_enabled field in the database.
	FieldReasoningEnabled = "reasoning_enabled"
	// FieldReasoningEffort holds the string denoting the reasoning_effort field in the database.
	FieldReasoningEffort = "reasoning_effort"
	// FieldTokenContextWindow holds the string denoting the token_context_window field in the database.
	FieldTokenContextWindow = "token_context_window"
	// FieldTokenMaxOutputTokens holds the string denoting the token_max_output_tokens field in the database.
	FieldTokenMaxOutputTokens = "token_max_output_tokens"
	// FieldCapabilityToolUse holds the string denoting the capability_tool_use field in the database.
	FieldCapabilityToolUse = "capability_tool_use"
	// FieldCapabilityVision holds the string denoting the capability_vision field in the database.
	FieldCapabilityVision = "capability_vision"
	// FieldCapabilityStructuredOutput holds the string denoting the capability_structured_output field in the database.
	FieldCapabilityStructuredOutput = "capability_structured_output"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// Table holds the table name of the kaguyamodelsinfo in the database.
	Table = "kaguya_models_info"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "kaguya_models_info"
	// ProviderInverseTable is the table name for the KaguyaProviderInfo entity.
	// It exists in this package in order to avoid circular dependency with the "kaguyaproviderinfo" package.
	ProviderInverseTable = "kaguya_provider_info"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_id"
)

// Columns holds all SQL columns for kaguyamodelsinfo fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldProviderID,
	FieldModelName,
	FieldModelID,
	FieldIsDefault,
	FieldIsTask,
	FieldReasoningEnabled,
	FieldReasoningEffort,
	FieldTokenContextWindow,
	FieldTokenMaxOutputTokens,
	FieldCapabilityToolUse,
	FieldCapabilityVision,
	FieldCapabilityStructuredOutput,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lyonmu/kaguya/internal/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ProviderIDValidator is a validator for the "provider_id" field. It is called by the builders before save.
	ProviderIDValidator func(string) error
	// ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	ModelNameValidator func(string) error
	// ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	ModelIDValidator func(string) error
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault consts.Status
	// IsTaskValidator is a validator for the "is_task" field. It is called by the builders before save.
	IsTaskValidator func(int) error
	// DefaultReasoningEnabled holds the default value on creation for the "reasoning_enabled" field.
	DefaultReasoningEnabled consts.Status
	// DefaultReasoningEffort holds the default value on creation for the "reasoning_effort" field.
	DefaultReasoningEffort consts.ReasoningEffort
	// DefaultCapabilityToolUse holds the default value on creation for the "capability_tool_use" field.
	DefaultCapabilityToolUse consts.Status
	// DefaultCapabilityVision holds the default value on creation for the "capability_vision" field.
	DefaultCapabilityVision consts.Status
	// DefaultCapabilityStructuredOutput holds the default value on creation for the "capability_structured_output" field.
	DefaultCapabilityStructuredOutput consts.Status
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the KaguyaModelsInfo queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByIsTask orders the results by the is_task field.
func ByIsTask(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsTask, opts...).ToFunc()
}

// ByReasoningEnabled orders the results by the reasoning_enabled field.
func ByReasoningEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningEnabled, opts...).ToFunc()
}

// ByReasoningEffort orders the results by the reasoning_effort field.
func ByReasoningEffort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningEffort, opts...).ToFunc()
}

// ByTokenContextWindow orders the results by the token_context_window field.
func ByTokenContextWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenContextWindow, opts...).ToFunc()
}

// ByTokenMaxOutputTokens orders the results by the token_max_output_tokens field.
func ByTokenMaxOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenMaxOutputTokens, opts...).ToFunc()
}

// ByCapabilityToolUse orders the results by the capability_tool_use field.
func ByCapabilityToolUse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityToolUse, opts...).ToFunc()
}

// ByCapabilityVision orders the results by the capability_vision field.
func ByCapabilityVision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityVision, opts...).ToFunc()
}

// ByCapabilityStructuredOutput orders the results by the capability_structured_output field.
func ByCapabilityStructuredOutput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityStructuredOutput, opts...).ToFunc()
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
