// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/lyonmu/kaguya/internal/consts"
	"github.com/lyonmu/kaguya/internal/ent/kaguyaaccesslog"
	"github.com/lyonmu/kaguya/internal/ent/kaguyamodelsinfo"
	"github.com/lyonmu/kaguya/internal/ent/kaguyaproviderinfo"
	"github.com/lyonmu/kaguya/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	kaguyaaccesslogMixin := schema.KaguyaAccessLog{}.Mixin()
	kaguyaaccesslogMixinHooks1 := kaguyaaccesslogMixin[1].Hooks()
	kaguyaaccesslog.Hooks[0] = kaguyaaccesslogMixinHooks1[0]
	kaguyaaccesslog.Hooks[1] = kaguyaaccesslogMixinHooks1[1]
	kaguyaaccesslogMixinFields0 := kaguyaaccesslogMixin[0].Fields()
	_ = kaguyaaccesslogMixinFields0
	kaguyaaccesslogMixinFields1 := kaguyaaccesslogMixin[1].Fields()
	_ = kaguyaaccesslogMixinFields1
	kaguyaaccesslogFields := schema.KaguyaAccessLog{}.Fields()
	_ = kaguyaaccesslogFields
	// kaguyaaccesslogDescCreatedAt is the schema descriptor for created_at field.
	kaguyaaccesslogDescCreatedAt := kaguyaaccesslogMixinFields1[0].Descriptor()
	// kaguyaaccesslog.DefaultCreatedAt holds the default value on creation for the created_at field.
	kaguyaaccesslog.DefaultCreatedAt = kaguyaaccesslogDescCreatedAt.Default.(func() time.Time)
	// kaguyaaccesslogDescUpdatedAt is the schema descriptor for updated_at field.
	kaguyaaccesslogDescUpdatedAt := kaguyaaccesslogMixinFields1[1].Descriptor()
	// kaguyaaccesslog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	kaguyaaccesslog.DefaultUpdatedAt = kaguyaaccesslogDescUpdatedAt.Default.(func() time.Time)
	// kaguyaaccesslog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	kaguyaaccesslog.UpdateDefaultUpdatedAt = kaguyaaccesslogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// kaguyaaccesslogDescAccessTime is the schema descriptor for access_time field.
	kaguyaaccesslogDescAccessTime := kaguyaaccesslogFields[1].Descriptor()
	// kaguyaaccesslog.DefaultAccessTime holds the default value on creation for the access_time field.
	kaguyaaccesslog.DefaultAccessTime = kaguyaaccesslogDescAccessTime.Default.(func() int64)
	// kaguyaaccesslogDescID is the schema descriptor for id field.
	kaguyaaccesslogDescID := kaguyaaccesslogMixinFields0[0].Descriptor()
	// kaguyaaccesslog.DefaultID holds the default value on creation for the id field.
	kaguyaaccesslog.DefaultID = kaguyaaccesslogDescID.Default.(func() string)
	// kaguyaaccesslog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	kaguyaaccesslog.IDValidator = func() func(string) error {
		validators := kaguyaaccesslogDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	kaguyamodelsinfoMixin := schema.KaguyaModelsInfo{}.Mixin()
	kaguyamodelsinfoMixinHooks1 := kaguyamodelsinfoMixin[1].Hooks()
	kaguyamodelsinfo.Hooks[0] = kaguyamodelsinfoMixinHooks1[0]
	kaguyamodelsinfo.Hooks[1] = kaguyamodelsinfoMixinHooks1[1]
	kaguyamodelsinfoMixinFields0 := kaguyamodelsinfoMixin[0].Fields()
	_ = kaguyamodelsinfoMixinFields0
	kaguyamodelsinfoMixinFields1 := kaguyamodelsinfoMixin[1].Fields()
	_ = kaguyamodelsinfoMixinFields1
	kaguyamodelsinfoFields := schema.KaguyaModelsInfo{}.Fields()
	_ = kaguyamodelsinfoFields
	// kaguyamodelsinfoDescCreatedAt is the schema descriptor for created_at field.
	kaguyamodelsinfoDescCreatedAt := kaguyamodelsinfoMixinFields1[0].Descriptor()
	// kaguyamodelsinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	kaguyamodelsinfo.DefaultCreatedAt = kaguyamodelsinfoDescCreatedAt.Default.(func() time.Time)
	// kaguyamodelsinfoDescUpdatedAt is the schema descriptor for updated_at field.
	kaguyamodelsinfoDescUpdatedAt := kaguyamodelsinfoMixinFields1[1].Descriptor()
	// kaguyamodelsinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	kaguyamodelsinfo.DefaultUpdatedAt = kaguyamodelsinfoDescUpdatedAt.Default.(func() time.Time)
	// kaguyamodelsinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	kaguyamodelsinfo.UpdateDefaultUpdatedAt = kaguyamodelsinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// kaguyamodelsinfoDescIsDefault is the schema descriptor for is_default field.
	kaguyamodelsinfoDescIsDefault := kaguyamodelsinfoFields[3].Descriptor()
	// kaguyamodelsinfo.DefaultIsDefault holds the default value on creation for the is_default field.
	kaguyamodelsinfo.DefaultIsDefault = consts.Status(kaguyamodelsinfoDescIsDefault.Default.(int))
	// kaguyamodelsinfoDescReasoningEnabled is the schema descriptor for reasoning_enabled field.
	kaguyamodelsinfoDescReasoningEnabled := kaguyamodelsinfoFields[4].Descriptor()
	// kaguyamodelsinfo.DefaultReasoningEnabled holds the default value on creation for the reasoning_enabled field.
	kaguyamodelsinfo.DefaultReasoningEnabled = consts.Status(kaguyamodelsinfoDescReasoningEnabled.Default.(int))
	// kaguyamodelsinfoDescReasoningEffort is the schema descriptor for reasoning_effort field.
	kaguyamodelsinfoDescReasoningEffort := kaguyamodelsinfoFields[5].Descriptor()
	// kaguyamodelsinfo.DefaultReasoningEffort holds the default value on creation for the reasoning_effort field.
	kaguyamodelsinfo.DefaultReasoningEffort = consts.ReasoningEffort(kaguyamodelsinfoDescReasoningEffort.Default.(string))
	// kaguyamodelsinfoDescCapabilityToolUse is the schema descriptor for capability_tool_use field.
	kaguyamodelsinfoDescCapabilityToolUse := kaguyamodelsinfoFields[8].Descriptor()
	// kaguyamodelsinfo.DefaultCapabilityToolUse holds the default value on creation for the capability_tool_use field.
	kaguyamodelsinfo.DefaultCapabilityToolUse = consts.Status(kaguyamodelsinfoDescCapabilityToolUse.Default.(int))
	// kaguyamodelsinfoDescCapabilityVision is the schema descriptor for capability_vision field.
	kaguyamodelsinfoDescCapabilityVision := kaguyamodelsinfoFields[9].Descriptor()
	// kaguyamodelsinfo.DefaultCapabilityVision holds the default value on creation for the capability_vision field.
	kaguyamodelsinfo.DefaultCapabilityVision = consts.Status(kaguyamodelsinfoDescCapabilityVision.Default.(int))
	// kaguyamodelsinfoDescCapabilityStructuredOutput is the schema descriptor for capability_structured_output field.
	kaguyamodelsinfoDescCapabilityStructuredOutput := kaguyamodelsinfoFields[10].Descriptor()
	// kaguyamodelsinfo.DefaultCapabilityStructuredOutput holds the default value on creation for the capability_structured_output field.
	kaguyamodelsinfo.DefaultCapabilityStructuredOutput = consts.Status(kaguyamodelsinfoDescCapabilityStructuredOutput.Default.(int))
	// kaguyamodelsinfoDescID is the schema descriptor for id field.
	kaguyamodelsinfoDescID := kaguyamodelsinfoMixinFields0[0].Descriptor()
	// kaguyamodelsinfo.DefaultID holds the default value on creation for the id field.
	kaguyamodelsinfo.DefaultID = kaguyamodelsinfoDescID.Default.(func() string)
	// kaguyamodelsinfo.IDValidator is a validator for the "id" field. It is called by the builders before save.
	kaguyamodelsinfo.IDValidator = func() func(string) error {
		validators := kaguyamodelsinfoDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	kaguyaproviderinfoMixin := schema.KaguyaProviderInfo{}.Mixin()
	kaguyaproviderinfoMixinHooks1 := kaguyaproviderinfoMixin[1].Hooks()
	kaguyaproviderinfo.Hooks[0] = kaguyaproviderinfoMixinHooks1[0]
	kaguyaproviderinfo.Hooks[1] = kaguyaproviderinfoMixinHooks1[1]
	kaguyaproviderinfoMixinFields0 := kaguyaproviderinfoMixin[0].Fields()
	_ = kaguyaproviderinfoMixinFields0
	kaguyaproviderinfoMixinFields1 := kaguyaproviderinfoMixin[1].Fields()
	_ = kaguyaproviderinfoMixinFields1
	kaguyaproviderinfoFields := schema.KaguyaProviderInfo{}.Fields()
	_ = kaguyaproviderinfoFields
	// kaguyaproviderinfoDescCreatedAt is the schema descriptor for created_at field.
	kaguyaproviderinfoDescCreatedAt := kaguyaproviderinfoMixinFields1[0].Descriptor()
	// kaguyaproviderinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	kaguyaproviderinfo.DefaultCreatedAt = kaguyaproviderinfoDescCreatedAt.Default.(func() time.Time)
	// kaguyaproviderinfoDescUpdatedAt is the schema descriptor for updated_at field.
	kaguyaproviderinfoDescUpdatedAt := kaguyaproviderinfoMixinFields1[1].Descriptor()
	// kaguyaproviderinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	kaguyaproviderinfo.DefaultUpdatedAt = kaguyaproviderinfoDescUpdatedAt.Default.(func() time.Time)
	// kaguyaproviderinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	kaguyaproviderinfo.UpdateDefaultUpdatedAt = kaguyaproviderinfoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// kaguyaproviderinfoDescAPIProtocol is the schema descriptor for api_protocol field.
	kaguyaproviderinfoDescAPIProtocol := kaguyaproviderinfoFields[1].Descriptor()
	// kaguyaproviderinfo.DefaultAPIProtocol holds the default value on creation for the api_protocol field.
	kaguyaproviderinfo.DefaultAPIProtocol = consts.ProviderProtocol(kaguyaproviderinfoDescAPIProtocol.Default.(string))
	// kaguyaproviderinfoDescID is the schema descriptor for id field.
	kaguyaproviderinfoDescID := kaguyaproviderinfoMixinFields0[0].Descriptor()
	// kaguyaproviderinfo.DefaultID holds the default value on creation for the id field.
	kaguyaproviderinfo.DefaultID = kaguyaproviderinfoDescID.Default.(func() string)
	// kaguyaproviderinfo.IDValidator is a validator for the "id" field. It is called by the builders before save.
	kaguyaproviderinfo.IDValidator = func() func(string) error {
		validators := kaguyaproviderinfoDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
