// Code generated by ent, DO NOT EDIT.

package kaguyaaccesslog

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the kaguyaaccesslog type in the database.
	Label = "kaguya_access_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldAccessIP holds the string denoting the access_ip field in the database.
	FieldAccessIP = "access_ip"
	// FieldAccessTime holds the string denoting the access_time field in the database.
	FieldAccessTime = "access_time"
	// FieldOs holds the string denoting the os field in the database.
	FieldOs = "os"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldBrowserName holds the string denoting the browser_name field in the database.
	FieldBrowserName = "browser_name"
	// FieldBrowserVersion holds the string denoting the browser_version field in the database.
	FieldBrowserVersion = "browser_version"
	// FieldBrowserEngineName holds the string denoting the browser_engine_name field in the database.
	FieldBrowserEngineName = "browser_engine_name"
	// FieldBrowserEngineVersion holds the string denoting the browser_engine_version field in the database.
	FieldBrowserEngineVersion = "browser_engine_version"
	// Table holds the table name of the kaguyaaccesslog in the database.
	Table = "kaguya_access_log"
)

// Columns holds all SQL columns for kaguyaaccesslog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldAccessIP,
	FieldAccessTime,
	FieldOs,
	FieldPlatform,
	FieldBrowserName,
	FieldBrowserVersion,
	FieldBrowserEngineName,
	FieldBrowserEngineVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lyonmu/kaguya/internal/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAccessTime holds the default value on creation for the "access_time" field.
	DefaultAccessTime func() int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the KaguyaAccessLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByAccessIP orders the results by the access_ip field.
func ByAccessIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessIP, opts...).ToFunc()
}

// ByAccessTime orders the results by the access_time field.
func ByAccessTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTime, opts...).ToFunc()
}

// ByOs orders the results by the os field.
func ByOs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOs, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByBrowserName orders the results by the browser_name field.
func ByBrowserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrowserName, opts...).ToFunc()
}

// ByBrowserVersion orders the results by the browser_version field.
func ByBrowserVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrowserVersion, opts...).ToFunc()
}

// ByBrowserEngineName orders the results by the browser_engine_name field.
func ByBrowserEngineName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrowserEngineName, opts...).ToFunc()
}

// ByBrowserEngineVersion orders the results by the browser_engine_version field.
func ByBrowserEngineVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBrowserEngineVersion, opts...).ToFunc()
}
