// Code generated by ent, DO NOT EDIT.

package kaguyamemoryrevision

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/kaguya/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldDeletedAt, v))
}

// PageID applies equality check predicate on the "page_id" field. It's identical to PageIDEQ.
func PageID(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldPageID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldVersion, v))
}

// CanonicalKey applies equality check predicate on the "canonical_key" field. It's identical to CanonicalKeyEQ.
func CanonicalKey(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldCanonicalKey, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldTitle, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldSummary, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldBody, v))
}

// Pinned applies equality check predicate on the "pinned" field. It's identical to PinnedEQ.
func Pinned(v bool) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldPinned, v))
}

// UserLocked applies equality check predicate on the "user_locked" field. It's identical to UserLockedEQ.
func UserLocked(v bool) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldUserLocked, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldExpiresAt, v))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldJobID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotNull(FieldDeletedAt))
}

// PageIDEQ applies the EQ predicate on the "page_id" field.
func PageIDEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldPageID, v))
}

// PageIDNEQ applies the NEQ predicate on the "page_id" field.
func PageIDNEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldPageID, v))
}

// PageIDIn applies the In predicate on the "page_id" field.
func PageIDIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldPageID, vs...))
}

// PageIDNotIn applies the NotIn predicate on the "page_id" field.
func PageIDNotIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldPageID, vs...))
}

// PageIDGT applies the GT predicate on the "page_id" field.
func PageIDGT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldPageID, v))
}

// PageIDGTE applies the GTE predicate on the "page_id" field.
func PageIDGTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldPageID, v))
}

// PageIDLT applies the LT predicate on the "page_id" field.
func PageIDLT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldPageID, v))
}

// PageIDLTE applies the LTE predicate on the "page_id" field.
func PageIDLTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldPageID, v))
}

// PageIDContains applies the Contains predicate on the "page_id" field.
func PageIDContains(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContains(FieldPageID, v))
}

// PageIDHasPrefix applies the HasPrefix predicate on the "page_id" field.
func PageIDHasPrefix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasPrefix(FieldPageID, v))
}

// PageIDHasSuffix applies the HasSuffix predicate on the "page_id" field.
func PageIDHasSuffix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasSuffix(FieldPageID, v))
}

// PageIDEqualFold applies the EqualFold predicate on the "page_id" field.
func PageIDEqualFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEqualFold(FieldPageID, v))
}

// PageIDContainsFold applies the ContainsFold predicate on the "page_id" field.
func PageIDContainsFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContainsFold(FieldPageID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldVersion, v))
}

// CanonicalKeyEQ applies the EQ predicate on the "canonical_key" field.
func CanonicalKeyEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldCanonicalKey, v))
}

// CanonicalKeyNEQ applies the NEQ predicate on the "canonical_key" field.
func CanonicalKeyNEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldCanonicalKey, v))
}

// CanonicalKeyIn applies the In predicate on the "canonical_key" field.
func CanonicalKeyIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldCanonicalKey, vs...))
}

// CanonicalKeyNotIn applies the NotIn predicate on the "canonical_key" field.
func CanonicalKeyNotIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldCanonicalKey, vs...))
}

// CanonicalKeyGT applies the GT predicate on the "canonical_key" field.
func CanonicalKeyGT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldCanonicalKey, v))
}

// CanonicalKeyGTE applies the GTE predicate on the "canonical_key" field.
func CanonicalKeyGTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldCanonicalKey, v))
}

// CanonicalKeyLT applies the LT predicate on the "canonical_key" field.
func CanonicalKeyLT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldCanonicalKey, v))
}

// CanonicalKeyLTE applies the LTE predicate on the "canonical_key" field.
func CanonicalKeyLTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldCanonicalKey, v))
}

// CanonicalKeyContains applies the Contains predicate on the "canonical_key" field.
func CanonicalKeyContains(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContains(FieldCanonicalKey, v))
}

// CanonicalKeyHasPrefix applies the HasPrefix predicate on the "canonical_key" field.
func CanonicalKeyHasPrefix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasPrefix(FieldCanonicalKey, v))
}

// CanonicalKeyHasSuffix applies the HasSuffix predicate on the "canonical_key" field.
func CanonicalKeyHasSuffix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasSuffix(FieldCanonicalKey, v))
}

// CanonicalKeyEqualFold applies the EqualFold predicate on the "canonical_key" field.
func CanonicalKeyEqualFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEqualFold(FieldCanonicalKey, v))
}

// CanonicalKeyContainsFold applies the ContainsFold predicate on the "canonical_key" field.
func CanonicalKeyContainsFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContainsFold(FieldCanonicalKey, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldKind, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContainsFold(FieldTitle, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContainsFold(FieldSummary, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContainsFold(FieldBody, v))
}

// AliasesIsNil applies the IsNil predicate on the "aliases" field.
func AliasesIsNil() predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIsNull(FieldAliases))
}

// AliasesNotNil applies the NotNil predicate on the "aliases" field.
func AliasesNotNil() predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotNull(FieldAliases))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldStatus, vs...))
}

// PinnedEQ applies the EQ predicate on the "pinned" field.
func PinnedEQ(v bool) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldPinned, v))
}

// PinnedNEQ applies the NEQ predicate on the "pinned" field.
func PinnedNEQ(v bool) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldPinned, v))
}

// UserLockedEQ applies the EQ predicate on the "user_locked" field.
func UserLockedEQ(v bool) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldUserLocked, v))
}

// UserLockedNEQ applies the NEQ predicate on the "user_locked" field.
func UserLockedNEQ(v bool) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldUserLocked, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotNull(FieldExpiresAt))
}

// ClaimsIsNil applies the IsNil predicate on the "claims" field.
func ClaimsIsNil() predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIsNull(FieldClaims))
}

// ClaimsNotNil applies the NotNil predicate on the "claims" field.
func ClaimsNotNil() predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotNull(FieldClaims))
}

// ActorEQ applies the EQ predicate on the "actor" field.
func ActorEQ(v Actor) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldActor, v))
}

// ActorNEQ applies the NEQ predicate on the "actor" field.
func ActorNEQ(v Actor) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldActor, v))
}

// ActorIn applies the In predicate on the "actor" field.
func ActorIn(vs ...Actor) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldActor, vs...))
}

// ActorNotIn applies the NotIn predicate on the "actor" field.
func ActorNotIn(vs ...Actor) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldActor, vs...))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldJobID, v))
}

// JobIDContains applies the Contains predicate on the "job_id" field.
func JobIDContains(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContains(FieldJobID, v))
}

// JobIDHasPrefix applies the HasPrefix predicate on the "job_id" field.
func JobIDHasPrefix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasPrefix(FieldJobID, v))
}

// JobIDHasSuffix applies the HasSuffix predicate on the "job_id" field.
func JobIDHasSuffix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasSuffix(FieldJobID, v))
}

// JobIDEqualFold applies the EqualFold predicate on the "job_id" field.
func JobIDEqualFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEqualFold(FieldJobID, v))
}

// JobIDContainsFold applies the ContainsFold predicate on the "job_id" field.
func JobIDContainsFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContainsFold(FieldJobID, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.FieldContainsFold(FieldReason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KaguyaMemoryRevision) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KaguyaMemoryRevision) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KaguyaMemoryRevision) predicate.KaguyaMemoryRevision {
	return predicate.KaguyaMemoryRevision(sql.NotPredicates(p))
}
