// Code generated by ent, DO NOT EDIT.

package kaguyamemorysource

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the kaguyamemorysource type in the database.
	Label = "kaguya_memory_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldSourceKey holds the string denoting the source_key field in the database.
	FieldSourceKey = "source_key"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldScopeKey holds the string denoting the scope_key field in the database.
	FieldScopeKey = "scope_key"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// FieldTurnID holds the string denoting the turn_id field in the database.
	FieldTurnID = "turn_id"
	// FieldProjectionVersion holds the string denoting the projection_version field in the database.
	FieldProjectionVersion = "projection_version"
	// FieldCursorPart holds the string denoting the cursor_part field in the database.
	FieldCursorPart = "cursor_part"
	// FieldContentHash holds the string denoting the content_hash field in the database.
	FieldContentHash = "content_hash"
	// FieldRawContent holds the string denoting the raw_content field in the database.
	FieldRawContent = "raw_content"
	// FieldDocumentPath holds the string denoting the document_path field in the database.
	FieldDocumentPath = "document_path"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// FieldPolicyEpoch holds the string denoting the policy_epoch field in the database.
	FieldPolicyEpoch = "policy_epoch"
	// Table holds the table name of the kaguyamemorysource in the database.
	Table = "kaguya_memory_source"
)

// Columns holds all SQL columns for kaguyamemorysource fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldSourceKey,
	FieldKind,
	FieldScopeKey,
	FieldConversationID,
	FieldTurnID,
	FieldProjectionVersion,
	FieldCursorPart,
	FieldContentHash,
	FieldRawContent,
	FieldDocumentPath,
	FieldState,
	FieldJobID,
	FieldCapturedAt,
	FieldPolicyEpoch,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lyonmu/kaguya/internal/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SourceKeyValidator is a validator for the "source_key" field. It is called by the builders before save.
	SourceKeyValidator func(string) error
	// ScopeKeyValidator is a validator for the "scope_key" field. It is called by the builders before save.
	ScopeKeyValidator func(string) error
	// DefaultConversationID holds the default value on creation for the "conversation_id" field.
	DefaultConversationID string
	// ConversationIDValidator is a validator for the "conversation_id" field. It is called by the builders before save.
	ConversationIDValidator func(string) error
	// DefaultTurnID holds the default value on creation for the "turn_id" field.
	DefaultTurnID string
	// TurnIDValidator is a validator for the "turn_id" field. It is called by the builders before save.
	TurnIDValidator func(string) error
	// DefaultProjectionVersion holds the default value on creation for the "projection_version" field.
	DefaultProjectionVersion int
	// ProjectionVersionValidator is a validator for the "projection_version" field. It is called by the builders before save.
	ProjectionVersionValidator func(int) error
	// DefaultCursorPart holds the default value on creation for the "cursor_part" field.
	DefaultCursorPart int
	// CursorPartValidator is a validator for the "cursor_part" field. It is called by the builders before save.
	CursorPartValidator func(int) error
	// DefaultContentHash holds the default value on creation for the "content_hash" field.
	DefaultContentHash string
	// ContentHashValidator is a validator for the "content_hash" field. It is called by the builders before save.
	ContentHashValidator func(string) error
	// DefaultRawContent holds the default value on creation for the "raw_content" field.
	DefaultRawContent string
	// DefaultDocumentPath holds the default value on creation for the "document_path" field.
	DefaultDocumentPath string
	// DocumentPathValidator is a validator for the "document_path" field. It is called by the builders before save.
	DocumentPathValidator func(string) error
	// DefaultJobID holds the default value on creation for the "job_id" field.
	DefaultJobID string
	// JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	JobIDValidator func(string) error
	// DefaultPolicyEpoch holds the default value on creation for the "policy_epoch" field.
	DefaultPolicyEpoch int64
	// PolicyEpochValidator is a validator for the "policy_epoch" field. It is called by the builders before save.
	PolicyEpochValidator func(int64) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Kind defines the type for the "kind" enum field.
type Kind string

// KindTurn is the default value of the Kind enum.
const DefaultKind = KindTurn

// Kind values.
const (
	KindTurn   Kind = "turn"
	KindNote   Kind = "note"
	KindImport Kind = "import"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindTurn, KindNote, KindImport:
		return nil
	default:
		return fmt.Errorf("kaguyamemorysource: invalid enum value for kind field: %q", k)
	}
}

// State defines the type for the "state" enum field.
type State string

// StatePending is the default value of the State enum.
const DefaultState = StatePending

// State values.
const (
	StatePending   State = "pending"
	StateClaimed   State = "claimed"
	StateProcessed State = "processed"
	StateNoop      State = "noop"
	StateFailed    State = "failed"
	StateExcluded  State = "excluded"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePending, StateClaimed, StateProcessed, StateNoop, StateFailed, StateExcluded:
		return nil
	default:
		return fmt.Errorf("kaguyamemorysource: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the KaguyaMemorySource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// BySourceKey orders the results by the source_key field.
func BySourceKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceKey, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByScopeKey orders the results by the scope_key field.
func ByScopeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScopeKey, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByTurnID orders the results by the turn_id field.
func ByTurnID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurnID, opts...).ToFunc()
}

// ByProjectionVersion orders the results by the projection_version field.
func ByProjectionVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectionVersion, opts...).ToFunc()
}

// ByCursorPart orders the results by the cursor_part field.
func ByCursorPart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCursorPart, opts...).ToFunc()
}

// ByContentHash orders the results by the content_hash field.
func ByContentHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentHash, opts...).ToFunc()
}

// ByRawContent orders the results by the raw_content field.
func ByRawContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawContent, opts...).ToFunc()
}

// ByDocumentPath orders the results by the document_path field.
func ByDocumentPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentPath, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByPolicyEpoch orders the results by the policy_epoch field.
func ByPolicyEpoch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyEpoch, opts...).ToFunc()
}
