// Code generated by ent, DO NOT EDIT.

package kaguyasysteminfo

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lyonmu/kaguya/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldDeletedAt, v))
}

// AgentMaxSteps applies equality check predicate on the "agent_max_steps" field. It's identical to AgentMaxStepsEQ.
func AgentMaxSteps(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldAgentMaxSteps, v))
}

// ContextCompactionPercent applies equality check predicate on the "context_compaction_percent" field. It's identical to ContextCompactionPercentEQ.
func ContextCompactionPercent(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldContextCompactionPercent, v))
}

// CommandTimeoutSeconds applies equality check predicate on the "command_timeout_seconds" field. It's identical to CommandTimeoutSecondsEQ.
func CommandTimeoutSeconds(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldCommandTimeoutSeconds, v))
}

// ChatMaxRetries applies equality check predicate on the "chat_max_retries" field. It's identical to ChatMaxRetriesEQ.
func ChatMaxRetries(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldChatMaxRetries, v))
}

// SystemPrompt applies equality check predicate on the "system_prompt" field. It's identical to SystemPromptEQ.
func SystemPrompt(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldSystemPrompt, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldUserAgent, v))
}

// DefaultModelID applies equality check predicate on the "default_model_id" field. It's identical to DefaultModelIDEQ.
func DefaultModelID(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldDefaultModelID, v))
}

// TaskModelID applies equality check predicate on the "task_model_id" field. It's identical to TaskModelIDEQ.
func TaskModelID(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldTaskModelID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotNull(FieldDeletedAt))
}

// AgentMaxStepsEQ applies the EQ predicate on the "agent_max_steps" field.
func AgentMaxStepsEQ(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldAgentMaxSteps, v))
}

// AgentMaxStepsNEQ applies the NEQ predicate on the "agent_max_steps" field.
func AgentMaxStepsNEQ(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldAgentMaxSteps, v))
}

// AgentMaxStepsIn applies the In predicate on the "agent_max_steps" field.
func AgentMaxStepsIn(vs ...int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldAgentMaxSteps, vs...))
}

// AgentMaxStepsNotIn applies the NotIn predicate on the "agent_max_steps" field.
func AgentMaxStepsNotIn(vs ...int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldAgentMaxSteps, vs...))
}

// AgentMaxStepsGT applies the GT predicate on the "agent_max_steps" field.
func AgentMaxStepsGT(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldAgentMaxSteps, v))
}

// AgentMaxStepsGTE applies the GTE predicate on the "agent_max_steps" field.
func AgentMaxStepsGTE(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldAgentMaxSteps, v))
}

// AgentMaxStepsLT applies the LT predicate on the "agent_max_steps" field.
func AgentMaxStepsLT(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldAgentMaxSteps, v))
}

// AgentMaxStepsLTE applies the LTE predicate on the "agent_max_steps" field.
func AgentMaxStepsLTE(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldAgentMaxSteps, v))
}

// ContextCompactionPercentEQ applies the EQ predicate on the "context_compaction_percent" field.
func ContextCompactionPercentEQ(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldContextCompactionPercent, v))
}

// ContextCompactionPercentNEQ applies the NEQ predicate on the "context_compaction_percent" field.
func ContextCompactionPercentNEQ(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldContextCompactionPercent, v))
}

// ContextCompactionPercentIn applies the In predicate on the "context_compaction_percent" field.
func ContextCompactionPercentIn(vs ...int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldContextCompactionPercent, vs...))
}

// ContextCompactionPercentNotIn applies the NotIn predicate on the "context_compaction_percent" field.
func ContextCompactionPercentNotIn(vs ...int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldContextCompactionPercent, vs...))
}

// ContextCompactionPercentGT applies the GT predicate on the "context_compaction_percent" field.
func ContextCompactionPercentGT(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldContextCompactionPercent, v))
}

// ContextCompactionPercentGTE applies the GTE predicate on the "context_compaction_percent" field.
func ContextCompactionPercentGTE(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldContextCompactionPercent, v))
}

// ContextCompactionPercentLT applies the LT predicate on the "context_compaction_percent" field.
func ContextCompactionPercentLT(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldContextCompactionPercent, v))
}

// ContextCompactionPercentLTE applies the LTE predicate on the "context_compaction_percent" field.
func ContextCompactionPercentLTE(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldContextCompactionPercent, v))
}

// CommandTimeoutSecondsEQ applies the EQ predicate on the "command_timeout_seconds" field.
func CommandTimeoutSecondsEQ(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldCommandTimeoutSeconds, v))
}

// CommandTimeoutSecondsNEQ applies the NEQ predicate on the "command_timeout_seconds" field.
func CommandTimeoutSecondsNEQ(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldCommandTimeoutSeconds, v))
}

// CommandTimeoutSecondsIn applies the In predicate on the "command_timeout_seconds" field.
func CommandTimeoutSecondsIn(vs ...int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldCommandTimeoutSeconds, vs...))
}

// CommandTimeoutSecondsNotIn applies the NotIn predicate on the "command_timeout_seconds" field.
func CommandTimeoutSecondsNotIn(vs ...int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldCommandTimeoutSeconds, vs...))
}

// CommandTimeoutSecondsGT applies the GT predicate on the "command_timeout_seconds" field.
func CommandTimeoutSecondsGT(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldCommandTimeoutSeconds, v))
}

// CommandTimeoutSecondsGTE applies the GTE predicate on the "command_timeout_seconds" field.
func CommandTimeoutSecondsGTE(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldCommandTimeoutSeconds, v))
}

// CommandTimeoutSecondsLT applies the LT predicate on the "command_timeout_seconds" field.
func CommandTimeoutSecondsLT(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldCommandTimeoutSeconds, v))
}

// CommandTimeoutSecondsLTE applies the LTE predicate on the "command_timeout_seconds" field.
func CommandTimeoutSecondsLTE(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldCommandTimeoutSeconds, v))
}

// ChatMaxRetriesEQ applies the EQ predicate on the "chat_max_retries" field.
func ChatMaxRetriesEQ(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldChatMaxRetries, v))
}

// ChatMaxRetriesNEQ applies the NEQ predicate on the "chat_max_retries" field.
func ChatMaxRetriesNEQ(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldChatMaxRetries, v))
}

// ChatMaxRetriesIn applies the In predicate on the "chat_max_retries" field.
func ChatMaxRetriesIn(vs ...int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldChatMaxRetries, vs...))
}

// ChatMaxRetriesNotIn applies the NotIn predicate on the "chat_max_retries" field.
func ChatMaxRetriesNotIn(vs ...int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldChatMaxRetries, vs...))
}

// ChatMaxRetriesGT applies the GT predicate on the "chat_max_retries" field.
func ChatMaxRetriesGT(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldChatMaxRetries, v))
}

// ChatMaxRetriesGTE applies the GTE predicate on the "chat_max_retries" field.
func ChatMaxRetriesGTE(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldChatMaxRetries, v))
}

// ChatMaxRetriesLT applies the LT predicate on the "chat_max_retries" field.
func ChatMaxRetriesLT(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldChatMaxRetries, v))
}

// ChatMaxRetriesLTE applies the LTE predicate on the "chat_max_retries" field.
func ChatMaxRetriesLTE(v int) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldChatMaxRetries, v))
}

// GlobalAgentsPathsIsNil applies the IsNil predicate on the "global_agents_paths" field.
func GlobalAgentsPathsIsNil() predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIsNull(FieldGlobalAgentsPaths))
}

// GlobalAgentsPathsNotNil applies the NotNil predicate on the "global_agents_paths" field.
func GlobalAgentsPathsNotNil() predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotNull(FieldGlobalAgentsPaths))
}

// SystemPromptEQ applies the EQ predicate on the "system_prompt" field.
func SystemPromptEQ(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldSystemPrompt, v))
}

// SystemPromptNEQ applies the NEQ predicate on the "system_prompt" field.
func SystemPromptNEQ(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldSystemPrompt, v))
}

// SystemPromptIn applies the In predicate on the "system_prompt" field.
func SystemPromptIn(vs ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldSystemPrompt, vs...))
}

// SystemPromptNotIn applies the NotIn predicate on the "system_prompt" field.
func SystemPromptNotIn(vs ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldSystemPrompt, vs...))
}

// SystemPromptGT applies the GT predicate on the "system_prompt" field.
func SystemPromptGT(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldSystemPrompt, v))
}

// SystemPromptGTE applies the GTE predicate on the "system_prompt" field.
func SystemPromptGTE(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldSystemPrompt, v))
}

// SystemPromptLT applies the LT predicate on the "system_prompt" field.
func SystemPromptLT(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldSystemPrompt, v))
}

// SystemPromptLTE applies the LTE predicate on the "system_prompt" field.
func SystemPromptLTE(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldSystemPrompt, v))
}

// SystemPromptContains applies the Contains predicate on the "system_prompt" field.
func SystemPromptContains(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContains(FieldSystemPrompt, v))
}

// SystemPromptHasPrefix applies the HasPrefix predicate on the "system_prompt" field.
func SystemPromptHasPrefix(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldHasPrefix(FieldSystemPrompt, v))
}

// SystemPromptHasSuffix applies the HasSuffix predicate on the "system_prompt" field.
func SystemPromptHasSuffix(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldHasSuffix(FieldSystemPrompt, v))
}

// SystemPromptEqualFold applies the EqualFold predicate on the "system_prompt" field.
func SystemPromptEqualFold(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEqualFold(FieldSystemPrompt, v))
}

// SystemPromptContainsFold applies the ContainsFold predicate on the "system_prompt" field.
func SystemPromptContainsFold(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContainsFold(FieldSystemPrompt, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContainsFold(FieldUserAgent, v))
}

// DefaultModelIDEQ applies the EQ predicate on the "default_model_id" field.
func DefaultModelIDEQ(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldDefaultModelID, v))
}

// DefaultModelIDNEQ applies the NEQ predicate on the "default_model_id" field.
func DefaultModelIDNEQ(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldDefaultModelID, v))
}

// DefaultModelIDIn applies the In predicate on the "default_model_id" field.
func DefaultModelIDIn(vs ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldDefaultModelID, vs...))
}

// DefaultModelIDNotIn applies the NotIn predicate on the "default_model_id" field.
func DefaultModelIDNotIn(vs ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldDefaultModelID, vs...))
}

// DefaultModelIDGT applies the GT predicate on the "default_model_id" field.
func DefaultModelIDGT(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldDefaultModelID, v))
}

// DefaultModelIDGTE applies the GTE predicate on the "default_model_id" field.
func DefaultModelIDGTE(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldDefaultModelID, v))
}

// DefaultModelIDLT applies the LT predicate on the "default_model_id" field.
func DefaultModelIDLT(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldDefaultModelID, v))
}

// DefaultModelIDLTE applies the LTE predicate on the "default_model_id" field.
func DefaultModelIDLTE(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldDefaultModelID, v))
}

// DefaultModelIDContains applies the Contains predicate on the "default_model_id" field.
func DefaultModelIDContains(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContains(FieldDefaultModelID, v))
}

// DefaultModelIDHasPrefix applies the HasPrefix predicate on the "default_model_id" field.
func DefaultModelIDHasPrefix(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldHasPrefix(FieldDefaultModelID, v))
}

// DefaultModelIDHasSuffix applies the HasSuffix predicate on the "default_model_id" field.
func DefaultModelIDHasSuffix(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldHasSuffix(FieldDefaultModelID, v))
}

// DefaultModelIDEqualFold applies the EqualFold predicate on the "default_model_id" field.
func DefaultModelIDEqualFold(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEqualFold(FieldDefaultModelID, v))
}

// DefaultModelIDContainsFold applies the ContainsFold predicate on the "default_model_id" field.
func DefaultModelIDContainsFold(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContainsFold(FieldDefaultModelID, v))
}

// TaskModelIDEQ applies the EQ predicate on the "task_model_id" field.
func TaskModelIDEQ(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEQ(FieldTaskModelID, v))
}

// TaskModelIDNEQ applies the NEQ predicate on the "task_model_id" field.
func TaskModelIDNEQ(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNEQ(FieldTaskModelID, v))
}

// TaskModelIDIn applies the In predicate on the "task_model_id" field.
func TaskModelIDIn(vs ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldIn(FieldTaskModelID, vs...))
}

// TaskModelIDNotIn applies the NotIn predicate on the "task_model_id" field.
func TaskModelIDNotIn(vs ...string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldNotIn(FieldTaskModelID, vs...))
}

// TaskModelIDGT applies the GT predicate on the "task_model_id" field.
func TaskModelIDGT(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGT(FieldTaskModelID, v))
}

// TaskModelIDGTE applies the GTE predicate on the "task_model_id" field.
func TaskModelIDGTE(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldGTE(FieldTaskModelID, v))
}

// TaskModelIDLT applies the LT predicate on the "task_model_id" field.
func TaskModelIDLT(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLT(FieldTaskModelID, v))
}

// TaskModelIDLTE applies the LTE predicate on the "task_model_id" field.
func TaskModelIDLTE(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldLTE(FieldTaskModelID, v))
}

// TaskModelIDContains applies the Contains predicate on the "task_model_id" field.
func TaskModelIDContains(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContains(FieldTaskModelID, v))
}

// TaskModelIDHasPrefix applies the HasPrefix predicate on the "task_model_id" field.
func TaskModelIDHasPrefix(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldHasPrefix(FieldTaskModelID, v))
}

// TaskModelIDHasSuffix applies the HasSuffix predicate on the "task_model_id" field.
func TaskModelIDHasSuffix(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldHasSuffix(FieldTaskModelID, v))
}

// TaskModelIDEqualFold applies the EqualFold predicate on the "task_model_id" field.
func TaskModelIDEqualFold(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldEqualFold(FieldTaskModelID, v))
}

// TaskModelIDContainsFold applies the ContainsFold predicate on the "task_model_id" field.
func TaskModelIDContainsFold(v string) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.FieldContainsFold(FieldTaskModelID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KaguyaSystemInfo) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KaguyaSystemInfo) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KaguyaSystemInfo) predicate.KaguyaSystemInfo {
	return predicate.KaguyaSystemInfo(sql.NotPredicates(p))
}
