basePath: /kaguya/api
definitions:
  chat.ChatReq:
    properties:
      messages:
        type: string
    required:
    - messages
    type: object
host: http://localhost:9024
info:
  contact:
    email: lyonmu@foxmail.com
    name: Lyon Mu
    url: https://github.com/lyonmu
  description: kaguya 后端
  license:
    name: MIT
    url: https://github.com/lyonmu/kaguya/blob/master/LICENSE
  title: kaguya Swagger API接口文档
  version: v0.0.1
paths:
  /v1/chat:
    get:
      description: 简单对话 chat
      parameters:
      - description: 用户发起的对话
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/chat.ChatReq'
      produces:
      - application/json
      responses: {}
      summary: 简单对话
      tags:
      - 对话
schemes:
- http
swagger: "2.0"
