// Code generated by ent, DO NOT EDIT.

package kaguyachatturn

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the kaguyachatturn type in the database.
	Label = "kaguya_chat_turn"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// FieldTurnIndex holds the string denoting the turn_index field in the database.
	FieldTurnIndex = "turn_index"
	// FieldUserContent holds the string denoting the user_content field in the database.
	FieldUserContent = "user_content"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldProviderName holds the string denoting the provider_name field in the database.
	FieldProviderName = "provider_name"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldAPIProtocol holds the string denoting the api_protocol field in the database.
	FieldAPIProtocol = "api_protocol"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldToolCalls holds the string denoting the tool_calls field in the database.
	FieldToolCalls = "tool_calls"
	// FieldFinishReason holds the string denoting the finish_reason field in the database.
	FieldFinishReason = "finish_reason"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldCachedTokens holds the string denoting the cached_tokens field in the database.
	FieldCachedTokens = "cached_tokens"
	// FieldReasoningTokens holds the string denoting the reasoning_tokens field in the database.
	FieldReasoningTokens = "reasoning_tokens"
	// FieldContextTokens holds the string denoting the context_tokens field in the database.
	FieldContextTokens = "context_tokens"
	// FieldContextWindow holds the string denoting the context_window field in the database.
	FieldContextWindow = "context_window"
	// FieldMessages holds the string denoting the messages field in the database.
	FieldMessages = "messages"
	// EdgeConversation holds the string denoting the conversation edge name in mutations.
	EdgeConversation = "conversation"
	// EdgeBlocks holds the string denoting the blocks edge name in mutations.
	EdgeBlocks = "blocks"
	// Table holds the table name of the kaguyachatturn in the database.
	Table = "kaguya_chat_turn"
	// ConversationTable is the table that holds the conversation relation/edge.
	ConversationTable = "kaguya_chat_turn"
	// ConversationInverseTable is the table name for the KaguyaConversation entity.
	// It exists in this package in order to avoid circular dependency with the "kaguyaconversation" package.
	ConversationInverseTable = "kaguya_conversation"
	// ConversationColumn is the table column denoting the conversation relation/edge.
	ConversationColumn = "conversation_id"
	// BlocksTable is the table that holds the blocks relation/edge.
	BlocksTable = "kaguya_chat_block"
	// BlocksInverseTable is the table name for the KaguyaChatBlock entity.
	// It exists in this package in order to avoid circular dependency with the "kaguyachatblock" package.
	BlocksInverseTable = "kaguya_chat_block"
	// BlocksColumn is the table column denoting the blocks relation/edge.
	BlocksColumn = "turn_id"
)

// Columns holds all SQL columns for kaguyachatturn fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldConversationID,
	FieldTurnIndex,
	FieldUserContent,
	FieldProviderID,
	FieldProviderName,
	FieldModelID,
	FieldModelName,
	FieldAPIProtocol,
	FieldStartedAt,
	FieldFinishedAt,
	FieldDurationMs,
	FieldToolCalls,
	FieldFinishReason,
	FieldInputTokens,
	FieldOutputTokens,
	FieldTotalTokens,
	FieldCachedTokens,
	FieldReasoningTokens,
	FieldContextTokens,
	FieldContextWindow,
	FieldMessages,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lyonmu/kaguya/internal/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ConversationIDValidator is a validator for the "conversation_id" field. It is called by the builders before save.
	ConversationIDValidator func(string) error
	// TurnIndexValidator is a validator for the "turn_index" field. It is called by the builders before save.
	TurnIndexValidator func(int64) error
	// DurationMsValidator is a validator for the "duration_ms" field. It is called by the builders before save.
	DurationMsValidator func(int64) error
	// ToolCallsValidator is a validator for the "tool_calls" field. It is called by the builders before save.
	ToolCallsValidator func(int64) error
	// InputTokensValidator is a validator for the "input_tokens" field. It is called by the builders before save.
	InputTokensValidator func(int64) error
	// OutputTokensValidator is a validator for the "output_tokens" field. It is called by the builders before save.
	OutputTokensValidator func(int64) error
	// TotalTokensValidator is a validator for the "total_tokens" field. It is called by the builders before save.
	TotalTokensValidator func(int64) error
	// CachedTokensValidator is a validator for the "cached_tokens" field. It is called by the builders before save.
	CachedTokensValidator func(int64) error
	// ReasoningTokensValidator is a validator for the "reasoning_tokens" field. It is called by the builders before save.
	ReasoningTokensValidator func(int64) error
	// ContextTokensValidator is a validator for the "context_tokens" field. It is called by the builders before save.
	ContextTokensValidator func(int64) error
	// DefaultContextWindow holds the default value on creation for the "context_window" field.
	DefaultContextWindow int
	// ContextWindowValidator is a validator for the "context_window" field. It is called by the builders before save.
	ContextWindowValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the KaguyaChatTurn queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByTurnIndex orders the results by the turn_index field.
func ByTurnIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTurnIndex, opts...).ToFunc()
}

// ByUserContent orders the results by the user_content field.
func ByUserContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserContent, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByProviderName orders the results by the provider_name field.
func ByProviderName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderName, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByAPIProtocol orders the results by the api_protocol field.
func ByAPIProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIProtocol, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByToolCalls orders the results by the tool_calls field.
func ByToolCalls(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolCalls, opts...).ToFunc()
}

// ByFinishReason orders the results by the finish_reason field.
func ByFinishReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishReason, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByCachedTokens orders the results by the cached_tokens field.
func ByCachedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedTokens, opts...).ToFunc()
}

// ByReasoningTokens orders the results by the reasoning_tokens field.
func ByReasoningTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningTokens, opts...).ToFunc()
}

// ByContextTokens orders the results by the context_tokens field.
func ByContextTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextTokens, opts...).ToFunc()
}

// ByContextWindow orders the results by the context_window field.
func ByContextWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextWindow, opts...).ToFunc()
}

// ByConversationField orders the results by conversation field.
func ByConversationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConversationStep(), sql.OrderByField(field, opts...))
	}
}

// ByBlocksCount orders the results by blocks count.
func ByBlocksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBlocksStep(), opts...)
	}
}

// ByBlocks orders the results by blocks terms.
func ByBlocks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlocksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newConversationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConversationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConversationTable, ConversationColumn),
	)
}
func newBlocksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlocksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BlocksTable, BlocksColumn),
	)
}
